r"""
Multi-Stage Branch-and-Price-and-Cut with Set Partitioning (MSBPCSP) Engine for VRPP.

This engine implements a state-of-the-art exact solver for the Vehicle Routing
Problem with Profits (VRPP), adapting the macro-architectural sequencing
framework of Barnhart, Hane, and Vance (2000) ["BHV2000"] to modern routing
heuristics and the Set Partitioning (SP) master formulation.

Paper-to-Implementation Mapping (BHV2000)
==========================================

§2 – ODIMCF Formulation → VRPP Set Partitioning
    Paper formulates arc-based multi-commodity flow (ODIMCF); this engine
    uses an equivalent column-based Set Partitioning Problem (SPP) over
    route variables λ_k.  Customer coverage constraints replace O-D flow
    conservation; the arc-capacity knapsack structure underpins LCI cuts.
    See: ``VRPPMasterProblem`` in master_problem.py.

§3 – Column Generation / Restricted Master Problem (RMP)
    LP relaxation of the SPP is solved iteratively.  New columns (routes)
    are generated by the RCSPP pricing subproblem (see §3.2 below).
    Phase I (Farkas pricing) guarantees initial LP feasibility without Big-M.
    Phase II switches to profit-maximising pricing once feasibility holds.
    Implementation: ``_column_generation_loop``, ``_solve_farkas_pricing_step``,
    ``_solve_pricing_step``.

§3.2 – Pricing Subproblem (RCSPP)
    Paper uses a shortest-path labelling algorithm on a time-space network.
    This engine uses a label-correcting DP with ng-route relaxation
    (Baldacci et al. 2011) to avoid the worst-case exponential state space.
    Reduced-cost formula: c'_k = c_k − Σ_i π_i δ_ik − Σ π_S · a_Sk
                                      − Σ γ_{lm} · α_{lm}^k  (LCI §4.2)
    Implementation: ``RCSPPSolver`` / ``_label_correcting_algorithm`` in
    rcspp_dp.py.

§4.1 – Lifted Cover Inequalities (LCI)
    Arc-capacity knapsack cuts lifted via the Gu, Nemhauser, Savelsbergh
    (1995a) exact sequence-independent procedure.  Both the physical-capacity
    engine (PhysicalCapacityLCIEngine) and the saturated-arc engine
    (SaturatedArcLCIEngine) are implemented; the latter matches §6 exactly.
    LCI duals γ_{lm} modify pricing arc costs as c'_{lm}^k = c_{lm}^k + γ_{lm}·α_{lm}^k.
    Implementation: cutting_planes.py; dual integration: rcspp_dp.py:
    ``_extend_label``.

§4.2 – LCI Dual Integration in Pricing
    Per-node α lifting coefficients are archived in the GlobalCutPool and
    persist across B&B nodes through the single shared master object, which is
    never rebuilt mid-search.  The
    composite dual dict emitted by ``get_reduced_cost_coefficients`` includes
    ``lci_duals`` and ``lci_node_alphas`` keys, which flow through to the
    label-extension step.
    Implementation: master_problem.py: ``get_reduced_cost_coefficients``;
    rcspp_dp.py: ``solve`` → ``_label_correcting_algorithm`` → ``_extend_label``.

§4.3 – Divergence Node Branching
    Two highest-λ fractional routes are traced step-by-step from the depot.
    The first node where they diverge is the branching node d.  arc_set_1
    contains the arc of the *shorter* path (path p in the paper); arc_set_2
    contains the remaining outgoing arcs including the longer path's arc.
    strategies.py swaps arc_p1/arc_p2 when path1 is longer, ensuring nxt_p1
    (shorter path's arc) heads the flow-sorted list and lands in arc_set_1.
    left_child  forbids arc_set_1 → longer path kept  (Paper's Child 1).
    right_child forbids arc_set_2 → shorter path kept (Paper's Child 2,
    explored FIRST per §3.2: "we choose the side where A(d,a2) is forbidden").
    Falls back to aggregate-flow heuristic when no common prefix exists.
    Implementation: ``MultiEdgePartitionBranching.find_divergence_node``
    in branching.py.

§5 – DFS Node Selection
    The B&B tree uses Depth-First Search (``DepthFirstStrategy``) to maximise
    LP basis reuse across parent → child transitions.  A warm-start snapshot
    of the parent's LP basis is stored in ``BranchNode.lp_basis`` and
    restored via ``master.restore_basis`` at the start of each child's CG loop.
    Implementation: ``search_strategy.py``, ``BranchAndBoundTree.add_node``,
    ``_column_generation_loop`` (``parent_basis`` arg).

§6 – Saturated-Arc LCI Separation
    For each arc (i,j) with fractional flow > 1 − ε, the set of routes using
    that arc forms a cover; the basic cover inequality is lifted and added.
    Implementation: ``SaturatedArcLCIEngine`` in cutting_planes.py.

Table 2 – CG at Root Only
    Set ``BPCParams.cg_at_root_only = True`` to replicate the Table 2
    experiment: column generation is skipped at all non-root nodes; only
    the pool built at the root is sifted and the LP re-solved.
    Implementation: ``_column_generation_loop`` (``cg_at_root_only`` arg).

Additional components not in BHV2000 (VRPP adaptations):
    - Ryan-Foster (1981) node-pair branching for the SPP.
    - Rounded Capacity Cuts (RCC, Lysgaard et al. 2004).
    - Subset-Row Inequalities (3-SRI, Jepsen et al. 2008).
    - GlobalCutPool: centralised cut registry; cuts persist across nodes
      through the single shared master object, which is never rebuilt mid-search.

Attributes:
    logger (logging.Logger): Module-level logger.
    _FARKAS_TOL (float): Numerical tolerance for Farkas pricing.

Example:
    >>> from logic.src.policies.route_construction.exact_and_decomposition_solvers.branch_and_price_and_cut.bpc_engine import run_bpc
    >>> dist_matrix = np.array([[0, 10], [10, 0]])
    >>> wastes = {1: 5.0}
    >>> routes, cost = run_bpc(dist_matrix, wastes, capacity=10, R=1, C=1)

References:
-----------
- Barnhart, C., Hane, C. A., & Vance, P. H. (2000). "Using branch-and-price-and-cut
  to solve origin-destination integer multicommodity flow problems."
  Operations Research, 48(2), 318–326.
- Barnhart, C., et al. (1998). "Branch-and-price: Column generation for solving
  huge integer programs." Operations Research, 46(3), 316–329.
- Baldacci, R., et al. (2011). "New state-space relaxation for the car-dependent VRP."
- Ryan, D. M., & Foster, B. A. (1981). "An integer programming approach to scheduling."
- Lysgaard, J., et al. (2004). "A new branch-and-cut algorithm for the capacitated VRP."
- Jepsen, M., et al. (2008). "Subset-row inequalities applied to the VRP with time windows."
- Gu, Z., Nemhauser, G. L., & Savelsbergh, M. W. P. (1995a). "Lifted cover inequalities
  for 0-1 integer programs."
- Wentges, P. (1997). "Weighted Dantzig-Wolfe decomposition for linear mixed-integer programming."
"""

import logging
import time
import warnings
from dataclasses import replace
from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple, Union

import gurobipy as gp
import numpy as np
from gurobipy import GRB

from logic.src.constants import MAX_CAPACITY_PERCENT
from logic.src.policies.helpers.operators.recreate_repair.greedy import greedy_insertion, greedy_profit_insertion
from logic.src.policies.helpers.solvers_and_matheuristics import (
    AnyBranchingConstraint,
    BranchAndBoundTree,
    CuttingPlaneEngine,
    PricingStatus,
    RCSPPSolver,
    Route,
    SeparationEngine,
    VRPPMasterProblem,
    create_cutting_plane_engine,
)
from logic.src.policies.helpers.solvers_and_matheuristics.branching.pruning import (
    BPCPruningException,
)
from logic.src.policies.helpers.solvers_and_matheuristics.branching.pruning import (
    apply_branching_to_master as _apply_branching_to_master,
)
from logic.src.policies.helpers.solvers_and_matheuristics.branching.pruning import (
    extract_forced_sets_from_constraints as _extract_forced_sets_from_constraints,
)
from logic.src.policies.helpers.solvers_and_matheuristics.branching.pruning import (
    perform_strong_branching as _perform_strong_branching,
)
from logic.src.policies.helpers.solvers_and_matheuristics.branching.pruning import (
    reset_master_constraints as _reset_master_constraints,  # noqa: F401  (re-exported for tests)
)
from logic.src.policies.helpers.solvers_and_matheuristics.lagrangian_relaxation.pre_pruning import (
    compute_lr_bound_at_node as _compute_lr_bound_at_node,
)
from logic.src.policies.helpers.solvers_and_matheuristics.vrpp_model import VRPPModel
from logic.src.tracking.viz_mixin import PolicyStateRecorder

from .params import MSBPCSPParams

logger = logging.getLogger(__name__)

# Minimum Farkas dual-ray weight to accept a column in Phase I pricing.
# Columns with weight below this threshold do not meaningfully contribute
# toward restoring LP feasibility and are discarded.
_FARKAS_TOL: float = 1e-6

# The empty-result relaxation retry (see run_ms_bpc_sp) is only applied on
# instances with at most this many customer nodes to bound the extra work.
# Instance size is not an optimality certificate.
_RELAX_RETRY_MAX_NODES = 8


MSBPCSPPruningException = BPCPruningException


def _column_generation_loop(  # noqa: C901
    master: VRPPMasterProblem,
    pricing_solver: RCSPPSolver,
    cut_engine: CuttingPlaneEngine,
    branching_constraints: Optional[List[AnyBranchingConstraint]],
    max_cg_iterations: int,
    max_cuts: int,
    time_limit: float,
    start_time: float,
    max_routes_per_pricing: int = 5,
    vehicle_limit: Optional[int] = None,
    optimality_gap: float = 1e-4,
    early_termination_gap: float = 1e-3,
    parent_basis: Optional[Any] = None,
    incumbent_value: float = -float("inf"),
    node_depth: int = 0,
    rc_tolerance: float = 1e-5,
    cut_orthogonality_threshold: float = 0.8,
    exact_mode: bool = False,
    cg_at_root_only: bool = False,
    branching_strategy: str = "divergence",
    rcspp_timeout: float = 30.0,
) -> Tuple[float, Dict[int, float], Optional[Any], bool]:
    """Run the Column Generation and Cutting Plane loop at a B&B node.

    Adopts the Barnhart et al. (1998) protocol for sequencing Cut Separation
    after CG convergence. Maintains the ng-route relaxation state and
    enforces strict elementarity for nodes in active SRI or node-pair
    branching constraints.

    When ``cg_at_root_only=True`` and ``node_depth > 0``, the pricing
    subproblem is not called: the LP is re-solved using only the columns
    already in the pool (sifted from the global pool at the root).  This
    replicates the "CG at root only" experiment from Table 2 of Barnhart,
    Hane, and Vance (2000), which trades bound quality for solve speed.

    Args:
        master (VRPPMasterProblem): Master problem instance.
        pricing_solver (RCSPPSolver): RCSPP pricing solver.
        cut_engine (CuttingPlaneEngine): Cutting plane separation engine.
        branching_constraints (Optional[List[AnyBranchingConstraint]]): Active constraints.
        max_cg_iterations (int): Maximum number of iterations per node.
        max_cuts (int): Maximum number of cuts per iteration.
        time_limit (Optional[float]): Time budget in seconds.
        start_time (float): Start timestamp of the overall solve.
        max_routes_per_pricing (int): Maximum number of columns to return.
        vehicle_limit (Optional[int]): Fleet size limit.
        optimality_gap (float): Target optimality gap.
        early_termination_gap (float): Heuristic stopping threshold.
        parent_basis (Optional[Any]): Gurobi basis from parent node.
        incumbent_value (float): Best known integer solution value.
        node_depth (int): Current B&B tree depth.
        rc_tolerance (float): Minimum reduced cost for column acceptance.
        cut_orthogonality_threshold (float): Minimum cut independence.
        cg_at_root_only (bool): If True, skips pricing at descendant nodes.
        branching_strategy (str): Active branching rule name.
        rcspp_timeout (float): Timeout for the RCSPP solver.

    Returns:
        Tuple[float, Dict[int, float], Optional[Any], bool]:
            (Objective value, Route values λ_k, LP basis, Timed out flag).
    """
    timed_out = False
    converged = False
    pricing_exhausted = False
    obj_val = -float("inf")
    route_vals: Dict[int, float] = {}
    prev_obj_val = -float("inf")
    _iteration = 0
    consecutive_pricing_timeouts = 0
    max_consecutive_pricing_timeouts = 3
    # Task 3: Fix Lagrangian default.
    # If no fleet limit is active, the worst-case number of vehicles is n_nodes.
    fleet_size: int = vehicle_limit if vehicle_limit is not None else master.n_nodes

    # Task 5: Arc Conflict Pre-check (Exactness Rule)
    # We must enforce strict elementarity for nodes involved in active SRIs or
    # Ryan-Foster node-pair branching to prevent the ng-relaxation from
    # bypassing these constraints via cycles.
    elementary_nodes: Set[int] = set()

    # Extract nodes from Ryan-Foster branches
    from logic.src.policies.helpers.solvers_and_matheuristics.branching import (
        NodeVisitationBranchingConstraint,
        RyanFosterBranchingConstraint,
    )

    for bc in branching_constraints or []:
        if isinstance(bc, RyanFosterBranchingConstraint):
            elementary_nodes.add(bc.node_r)
            elementary_nodes.add(bc.node_s)
        elif isinstance(bc, NodeVisitationBranchingConstraint) and bc.forced:
            # Force nodes are also strictly elementary to prevent cyclic bypass
            elementary_nodes.add(bc.node)

    # Extract nodes from active SRI subsets
    for subset in master.active_sri_cuts.keys():
        elementary_nodes.update(subset)

    if elementary_nodes:
        added_elem = pricing_solver.enforce_elementarity(list(elementary_nodes))
        if added_elem > 0:
            logger.info(
                f"[Theoretical Hardening] Enforcing strict elementarity for "
                f"{len(elementary_nodes)} nodes (SRI/Ryan-Foster parity)."
            )

    # Task 5: Arc Conflict Pre-check (Exactness Rule)
    # Scan branching constraints for conflicting must_use arcs.
    # At most one must_use arc can exit node u, and at most one can enter node v.
    from logic.src.policies.helpers.solvers_and_matheuristics.branching import EdgeBranchingConstraint

    out_arcs: Dict[int, int] = {}
    in_arcs: Dict[int, int] = {}
    for bc in branching_constraints or []:
        if isinstance(bc, EdgeBranchingConstraint) and bc.must_use:
            if bc.u in out_arcs and out_arcs[bc.u] != bc.v:
                raise RuntimeError(f"Conflicting must_use out-arcs at node {bc.u}")
            if bc.v in in_arcs and in_arcs[bc.v] != bc.u:
                raise RuntimeError(f"Conflicting must_use in-arcs at node {bc.v}")
            out_arcs[bc.u] = bc.v
            in_arcs[bc.v] = bc.u

    for _iteration in range(max_cg_iterations):
        if time_limit is not None and time_limit > 0 and (time.perf_counter() - start_time) > time_limit:
            timed_out = True
            break

        # PHASE 1: Column Generation (price until convergence)
        _inner_iter = 0
        while True:
            if time_limit is not None and time_limit > 0 and (time.perf_counter() - start_time) > time_limit:
                timed_out = True
                break

            # Basis restoration relocated after structural master updates
            # (branching, constraints, sifting) but before the core LP solve.
            if _inner_iter == 0 and isinstance(parent_basis, tuple):
                master.restore_basis(*parent_basis)

            # Only sift the pool after at least one LP solve has occurred at this node,
            # so the duals reflect the current node's constraint set.
            if _inner_iter > 0 and hasattr(master, "sift_global_column_pool"):
                duals = master.get_reduced_cost_coefficients()
                if duals:
                    # Pass all composite duals including LCI to sift_global_column_pool.
                    # This ensures columns re-activated from the global pool are evaluated
                    # against the full dual signal, including LCI penalties.
                    reactivated = master.sift_global_column_pool(
                        node_duals=duals["node_duals"],
                        rcc_duals=duals["rcc_duals"],
                        sri_duals=duals["sri_duals"],
                        edge_clique_duals=duals["edge_clique_duals"],
                        lci_duals=duals.get("lci_duals", {}),
                        lci_node_alphas=duals.get("lci_node_alphas", {}),
                        branching_constraints=branching_constraints,
                    )
                    if reactivated > 0:
                        # Re-apply branching filters to any newly activated columns.
                        # Sifting sets UB=1.0 for all positive-RC columns regardless of branching,
                        # so we must re-enforce the branching constraints immediately.
                        _apply_branching_to_master(
                            master, branching_constraints or [], branching_strategy=branching_strategy
                        )
                        # After the UB-reset inside _apply_branching_to_master, re-disable any
                        # non-elementary (cyclic) routes that cycle detection had suppressed.
                        # Without this, the sifting→reset→LP cycle keeps re-selecting the same
                        # cyclic routes, causing an infinite loop within one day's BPC solve.
                        for _nr, _nv in zip(master.routes, master.lambda_vars, strict=False):
                            if _nv.UB > 0.5 and len(set(_nr.nodes)) != len(_nr.nodes):
                                _nv.UB = 0.0
                        _inner_iter += 1
                        continue

            try:
                # Bound the LP solve to remaining wall-clock time so a single degenerate
                # master LP cannot blow past the node's overall time budget. Python-side
                # time checks only fire between Gurobi calls, so a single optimize() call
                # with no TimeLimit can overshoot the global limit on degenerate instances.
                if time_limit is not None and time_limit > 0 and master.model is not None:
                    _remaining_t = max(0.1, time_limit - (time.perf_counter() - start_time))
                    master.model.Params.TimeLimit = _remaining_t
                obj_val, route_vals = master.solve_lp_relaxation()  # type: ignore[assignment]
                if obj_val is None:
                    raise RuntimeError("LP relaxation returned non-optimal status at B&B node")

                if master.model is None or master.model.Status == GRB.INFEASIBLE:
                    logger.info("RMP node is infeasible. Starting Phase I Farkas Pricing.")
                    farkas = getattr(master, "farkas_duals", None)
                    if not farkas:
                        raise RuntimeError(
                            "LP is infeasible but Farkas duals are unavailable. "
                            "Gurobi may have returned INF_OR_UNBD — check model bounds."
                        )
                    if time_limit and time_limit > 0:
                        _elapsed_in_node = time.perf_counter() - start_time
                        _rem_t = max(0.1, time_limit - _elapsed_in_node)
                        _rem_t = min(_rem_t, 5.0)  # hard cap: no single RCSPP call exceeds 5s
                    else:
                        _rem_t = 5.0
                    added, farkas_exhausted = _solve_farkas_pricing_step(
                        master,
                        pricing_solver,
                        branching_constraints,  # type: ignore[arg-type]
                        farkas,
                        timeout=_rem_t,
                        exact_mode=exact_mode,
                    )
                    # If the pricer timed out, it cannot certify that no improving
                    # column exists. Track consecutive timeouts and bail out of CG
                    # when they accumulate — spinning here wastes the entire budget.
                    pricer_timed_out = getattr(pricing_solver, "_timed_out", False)
                    if pricer_timed_out:
                        consecutive_pricing_timeouts += 1
                        if consecutive_pricing_timeouts >= max_consecutive_pricing_timeouts:
                            logger.warning(
                                f"CG aborting: {consecutive_pricing_timeouts} consecutive "
                                "RCSPP timeouts. Budget too tight for exact pricing at this node."
                            )
                            timed_out = True
                            break
                    else:
                        consecutive_pricing_timeouts = 0
                    if added == 0:
                        if not farkas_exhausted:
                            timed_out = True
                            break
                        raise RuntimeError("LP infeasible at B&B node - Farkas pricing failed to find columns")
                    _inner_iter += 1
                    continue

                # Fix 1: Phase I → Phase II transition (Barnhart et al. 2000, §3).
                # After Farkas pricing restores feasibility (obj_val becomes finite),
                # switch route objectives from 0.0 (Phase I) back to profit (Phase II)
                # so the LP correctly maximises route profits going forward.
                if master.phase == 1 and master.model is not None and master.model.Status == GRB.OPTIMAL:
                    master.set_phase(2)
                    logger.info(
                        "Phase I complete — LP feasibility restored (GRB.OPTIMAL). "
                        "Switching to Phase II (profit maximization)."
                    )

            except Exception as e:
                if "Farkas pricing failed" in str(e):
                    raise
                raise RuntimeError("LP relaxation failed at B&B node") from e

            # Paper Table 2: "CG at root only" mode — skip pricing at non-root nodes.
            # The global column pool (built during root CG) is already sifted above;
            # no new columns are generated, so we converge immediately.
            if cg_at_root_only and node_depth > 0:
                # A restricted descendant LP has no full pricing certificate.
                timed_out = True
                break

            _elapsed = time.perf_counter() - start_time
            _remaining = max(0.1, time_limit - _elapsed) if time_limit is not None and time_limit > 0 else None
            _rem_t = (
                min(_remaining, time_limit * 0.40)
                if _remaining is not None and time_limit is not None and time_limit > 0 and node_depth == 0
                else _remaining
            )
            added, pricing_exhausted = _solve_pricing_step(
                master,
                pricing_solver,
                branching_constraints,
                max_routes=max(max_routes_per_pricing, 50),  # return more routes per call
                optimality_gap=optimality_gap,
                rc_tolerance=rc_tolerance,
                timeout=_rem_t,
                exact_mode=exact_mode,
            )
            # Consecutive RCSPP timeout detection.
            # A timed-out pricer returns partial results — it cannot certify
            # that no improving column exists. Spinning here burns the entire
            # budget without converging. Abort CG after N consecutive timeouts.
            if getattr(pricing_solver, "_timed_out", False):
                consecutive_pricing_timeouts += 1
                if consecutive_pricing_timeouts >= max_consecutive_pricing_timeouts:
                    logger.warning(
                        f"CG aborting at depth {node_depth}: "
                        f"{consecutive_pricing_timeouts} consecutive RCSPP timeouts. "
                        "Treating best available LP solution as node result."
                    )
                    timed_out = True
                    break
            else:
                consecutive_pricing_timeouts = 0

            if added == 0:
                if not pricing_exhausted:
                    logger.warning(
                        f"CG incomplete at depth {node_depth}: 0 columns added but pricing was not exhausted "
                        f"(status={getattr(pricing_solver, 'pricing_status', None)}, "
                        f"timed_out={getattr(pricing_solver, '_timed_out', False)}, "
                        f"last_max_rc={getattr(pricing_solver, 'last_max_rc', None):.4f})."
                    )
                    timed_out = True
                    break

                # Task 1b: Check for fractional cycles in ng-relaxation if CG has converged
                # locally. Dynamic ng-expansion serves as a lightweight cut separation.
                cycles: List[Tuple[int, ...]] = []
                for idx, val in route_vals.items():
                    if val > 0.1:
                        route = master.routes[idx]
                        route_cycles = _detect_cycles(route.nodes)
                        if route_cycles:
                            cycles.extend(route_cycles)

                if cycles:
                    added_ng = pricing_solver.expand_ng_neighborhoods(cycles)

                    # Task 1: Physically disable the cyclic columns in the Master Problem.
                    # Just expanding ng-sets is insufficient if the cyclic column remains
                    # active and dominating in the current RMP.
                    for idx, val in route_vals.items():
                        if val > 1e-4:
                            route = master.routes[idx]
                            if len(set(route.nodes)) != len(route.nodes):
                                master.lambda_vars[idx].UB = 0.0

                    if added_ng > 0:
                        logger.info(
                            f"[Dynamic ng-Expansion] Added {added_ng} neighborhood pairs "
                            f"to suppress {len(cycles)} cycles in iteration {_iteration}."
                        )
                        continue  # Re-run pricing with tightened relaxation

                # Truly converged for this cut-iteration
                converged = True
                break

            # Task 2b: Periodic Column Purging
            if _inner_iter > 0 and _inner_iter % 20 == 0:
                purged = master.purge_useless_columns(tolerance=-0.1)
                if purged > 0:
                    logger.info(f"Periodic purge removed {purged} useless columns.")

            _inner_iter += 1

        # Fix 3: Lagrangian UB check — only valid AFTER CG convergence.
        # Per Barnhart et al. (2000) §4, z_UB = z_LP + K * max_rc is a valid
        # upper bound only when all pricing subproblems have been exhausted
        # (no more positive reduced cost columns). Computing it mid-CG yields
        # an invalid, overly tight bound that can prune optimal nodes.
        # Lagrangian UB is only valid when CG has fully converged: i.e., the pricing
        # subproblem confirmed that NO column with positive reduced cost exists.
        # If we compute it while positive-RC columns may still exist (e.g., the batch
        # was capped by max_routes_per_pricing), last_max_rc underestimates the true
        # max RC, producing an UB that is tighter than valid and can prune optimal nodes.
        if (
            converged
            and pricing_exhausted
            and not timed_out
            and hasattr(pricing_solver, "last_max_rc")
        ):
            max_rc = getattr(pricing_solver, "last_max_rc", -float("inf"))
            effective_fleet = fleet_size if fleet_size > 0 else master.n_nodes
            lagrangian_ub = obj_val + (effective_fleet * max(0.0, max_rc))

            logger.info(f"CG Iter {_iteration}: RMP={obj_val:.4f}, max_rc={max_rc:.6f}, z_UB={lagrangian_ub:.4f}")

            if lagrangian_ub < incumbent_value - 1e-6:
                logger.info(f"Exact Pruning: z_UB {lagrangian_ub:.4f} < Incumbent {incumbent_value:.4f}")
                raise MSBPCSPPruningException(f"Node pruned by exact Lagrangian bound: {lagrangian_ub}")

            # Task 11: Heuristic Early Termination
            # Allows stopping column generation early if the Lagrangian gap is
            # sufficiently small, even if positive reduced cost columns exist.
            if incumbent_value > -float("inf"):
                gap_to_incumbent = (lagrangian_ub - incumbent_value) / max(1.0, abs(incumbent_value))
                if gap_to_incumbent <= early_termination_gap:
                    logger.warning(
                        "Heuristic early termination: bound gap %.6f <= threshold %.2e. "
                        "Solution optimality is NOT guaranteed.",
                        gap_to_incumbent,
                        early_termination_gap,
                    )
                    converged = True
                    break

        if timed_out:
            break

        # PHASE 2: Cutting Planes — Task 11: only separate when LP is optimal
        cuts_added = _separate_cuts(
            master,
            cut_engine,
            max_cuts,
            iteration=_iteration,
            node_depth=node_depth,
            cut_orthogonality_threshold=cut_orthogonality_threshold,
        )

        if cuts_added == 0:
            converged = True
            break

        # Fix 4 / Task 10 (SOTA): Tail-Off Management with relative tolerance.
        # Using absolute delta is fragile for problems with large objective values.
        # Relative delta normalises by objective magnitude for consistent behaviour.
        obj_delta = abs(obj_val - prev_obj_val) if _iteration > 0 else float("inf")
        denominator = max(1.0, abs(obj_val))
        relative_delta = obj_delta / denominator
        if relative_delta < 1e-5:
            logger.info(
                f"Tail-off detected: relative delta {relative_delta:.8f} < 1e-5 "
                f"(abs delta={obj_delta:.6f}, |obj|={denominator:.4f}). Stopping separation."
            )
            converged = True
            break
        prev_obj_val = obj_val

    # One final LP solve to get consistent obj_val / route_vals after any cuts/columns
    obj_val, route_vals = master.solve_lp_relaxation()  # type: ignore[assignment]

    # Warn only when the iteration cap truncated an unconverged loop
    if not converged and not timed_out and _iteration == max_cg_iterations - 1:
        warnings.warn(
            f"CG+Cut loop hit max_cg_iterations={max_cg_iterations} without full convergence.",
            stacklevel=3,
        )
        timed_out = True

    final_basis = master.save_basis()
    return obj_val, route_vals, final_basis, timed_out


# ---------------------------------------------------------------------------
# Static Helpers for Master Problem State Management
# ---------------------------------------------------------------------------






def _solve_farkas_pricing_step(
    master: VRPPMasterProblem,
    pricing_solver: RCSPPSolver,
    branching_constraints: List[AnyBranchingConstraint],
    farkas_duals: Any,
    max_routes: int = 5,
    timeout: float = 5.0,
    exact_mode: bool = False,
) -> Tuple[int, bool]:
    """Phase I Pricing: Solve RCSPP with the Farkas dual ray to restore feasibility.

    Implements the 2-Phase method by resolving LP primary infeasibility without
    Big-M artificial variables. The Farkas ray identifies the direction of
    infeasibility, guiding the DP pricer to find columns that restore the
    mandatory coverage basis.

    Args:
        master (VRPPMasterProblem): The master problem instance.
        pricing_solver (RCSPPSolver): The RCSPP solver for pricing.
        branching_constraints (List[AnyBranchingConstraint]): Active branching constraints.
        farkas_duals (Any): Dual values from the Farkas ray.
        max_routes (int): Maximum number of routes to return.
        timeout (Optional[float]): Time limit for the pricing step.
        exact_mode (bool): Whether exact pricing is enforced.

    Returns:
        Tuple[int, bool]: (Number of routes added, whether pricing was exhausted).
    """
    # Task 3/6: Extract forced nodes and RF conflicts for DP enforcement
    forced_nodes: Set[int] = set()
    rf_conflicts: Dict[int, Set[int]] = {}

    from logic.src.policies.helpers.solvers_and_matheuristics.branching import (
        NodeVisitationBranchingConstraint,
        RyanFosterBranchingConstraint,
    )

    for bc in branching_constraints or []:
        if isinstance(bc, NodeVisitationBranchingConstraint) and bc.forced:
            forced_nodes.add(bc.node)
        elif isinstance(bc, RyanFosterBranchingConstraint) and not bc.together:
            node_r, node_s = bc.node_r, bc.node_s
            rf_conflicts.setdefault(node_r, set()).add(node_s)
            rf_conflicts.setdefault(node_s, set()).add(node_r)

    # Solve subproblem
    routes: List[Route] = pricing_solver.solve(
        dual_values=farkas_duals,
        branching_constraints=branching_constraints,
        max_routes=max_routes,
        forced_nodes=forced_nodes,
        rf_conflicts=rf_conflicts,
        is_farkas=True,
        exact_mode=exact_mode,
        timeout=timeout,
    )

    added = 0
    for r in routes:
        # Phase I (Feasibility) Sign Convention:
        # Reduced cost is calculated using Farkas duals. In Phase I, we search
        # for columns with POSITIVE reduced cost to resolve infeasibility.
        rc = r.reduced_cost if r.reduced_cost is not None else r.profit
        if rc > _FARKAS_TOL and master.add_route(r):
            added += 1

    pricer_status = getattr(pricing_solver, "pricing_status", PricingStatus.PARTIAL)
    pricer_timed_out = getattr(pricing_solver, "_timed_out", False)
    last_max_rc = getattr(pricing_solver, "last_max_rc", -float("inf"))

    # Explicit certification: only an exhaustive solve with no timeout and
    # last_max_rc <= _FARKAS_TOL can certify exhaustion.
    exhausted = (
        pricer_status == PricingStatus.EXHAUSTIVE
        and not pricer_timed_out
        and last_max_rc <= _FARKAS_TOL
    )
    return added, exhausted


def _separate_cuts(
    master: VRPPMasterProblem,
    cut_engine: CuttingPlaneEngine,
    max_cuts: int,
    iteration: int = 0,
    node_depth: int = 0,
    cut_orthogonality_threshold: float = 0.8,
) -> int:
    """Separate and add valid inequalities using the configured cutting plane engine.

    This is a modular wrapper that delegates to the specific cutting plane
    engine (RCC, fleet_cover, etc.) configured by the user.

    Args:
        master (VRPPMasterProblem): Master problem instance.
        cut_engine (CuttingPlaneEngine): Cutting plane separation engine.
        max_cuts (int): Maximum number of cuts to add.
        iteration (int): Current B&B node iteration index.
        node_depth (int): Current B&B tree depth.
        cut_orthogonality_threshold (float): Minimum cosine distance between cut vectors.

    Returns:
        int: Number of cuts added.
    """
    return cut_engine.separate_and_add_cuts(
        master,
        max_cuts,
        iteration=iteration,
        node_depth=node_depth,
        cut_orthogonality_threshold=cut_orthogonality_threshold,
    )


def _solve_pricing_step(
    master: VRPPMasterProblem,
    pricing_solver: RCSPPSolver,
    branching_constraints: Optional[List[AnyBranchingConstraint]] = None,
    max_routes: int = 5,
    optimality_gap: float = 1e-4,
    rc_tolerance: float = 1e-5,
    timeout: Optional[float] = None,
    exact_mode: bool = False,
) -> Tuple[int, bool]:
    """Phase II Pricing: Solve the RCSPP pricing subproblem for profitable columns.

    Utilizes the current dual signal—optionally stabilized via Exponential
    Dual Smoothing (Wentges 1997)—to identify routes with positive reduced cost.

    Args:
        master (VRPPMasterProblem): Master problem instance.
        pricing_solver (RCSPPSolver): RCSPP solver for pricing.
        branching_constraints (Optional[List[AnyBranchingConstraint]]): Active branching constraints.
        max_routes (int): Maximum number of routes to return.
        optimality_gap (float): Target optimality gap.
        rc_tolerance (float): Minimum reduced cost to accept a column.
        timeout (Optional[float]): Time limit for the pricing step.
        exact_mode (bool): Whether exact pricing is enforced.

    Returns:
        Tuple[int, bool]: (Number of columns added, whether pricing was exhausted).
    """
    dual_values = master.get_reduced_cost_coefficients()

    # Task 3/6: Extract forced nodes and RF conflicts for DP enforcement
    forced_nodes: Set[int] = set()
    rf_conflicts: Dict[int, Set[int]] = {}

    from logic.src.policies.helpers.solvers_and_matheuristics.branching import (
        NodeVisitationBranchingConstraint,
        RyanFosterBranchingConstraint,
    )

    for bc in branching_constraints or []:
        if isinstance(bc, NodeVisitationBranchingConstraint) and bc.forced:
            forced_nodes.add(bc.node)
        elif isinstance(bc, RyanFosterBranchingConstraint) and not bc.together:
            node_r, node_s = bc.node_r, bc.node_s
            rf_conflicts.setdefault(node_r, set()).add(node_s)
            rf_conflicts.setdefault(node_s, set()).add(node_r)

    # RCSPPSolver.solve() handles composite dual dictionaries and branching.
    routes: List[Route] = pricing_solver.solve(
        dual_values=dual_values,
        max_routes=max_routes,
        branching_constraints=branching_constraints,
        forced_nodes=forced_nodes,
        rf_conflicts=rf_conflicts,
        exact_mode=exact_mode,
        timeout=timeout,
    )

    added = 0
    # routes is now a List[Route] from RCSPPSolver.solve
    for route in routes:
        # Phase II (Optimality) Sign Convention:
        # VRPP is a MAXIMIZATION problem. Pricing subproblem searches for columns
        # with POSITIVE reduced cost (rc > 0) to improve the objective.
        rc = route.reduced_cost if route.reduced_cost is not None else route.profit
        if rc > rc_tolerance and master.add_route(route):
            added += 1

    pricer_status = getattr(pricing_solver, "pricing_status", PricingStatus.PARTIAL)
    pricer_timed_out = getattr(pricing_solver, "_timed_out", False)
    last_max_rc = getattr(pricing_solver, "last_max_rc", -float("inf"))

    # Explicit pricing certification: only an EXHAUSTIVE solve that didn't time out
    # with maximum reduced cost <= rc_tolerance can certify exhaustion.
    exhausted = (
        pricer_status == PricingStatus.EXHAUSTIVE
        and not pricer_timed_out
        and last_max_rc <= rc_tolerance
    )
    return added, exhausted


def _detect_cycles(nodes: List[int]) -> List[Tuple[int, ...]]:
    """
    Detect cyclic node sequences in a route (excluding the depot).

    Identifies segments like (i, j, k, i) where a customer node is visited
    more than once. These cycles violate the ng-route relaxation if the
    intermediate nodes are outside the neighborhood of the cycle origin.

    Args:
        nodes: Sequence of node IDs.

    Returns:
        List[Tuple[int, ...]]: List of node tuples forming cycles.
    """
    seen: Dict[int, int] = {}
    cycles: List[Tuple[int, ...]] = []
    for i, node in enumerate(nodes):
        if node == 0:
            continue
        if node in seen:
            # Extract the cycle from the previous occurrence to the current one
            cycle = tuple(nodes[seen[node] : i + 1])
            cycles.append(cycle)
            # Update index to detect nested or subsequent cycles involving this node
            seen[node] = i
        else:
            seen[node] = i
    return cycles


def _is_solution_integer(routes: List[Route], route_values: Dict[int, float], tol: float = 1e-6) -> bool:
    """
    Check if LP solution is integer and strictly elementary.

    Args:
        routes: List of all routes in the Master Problem.
        route_values: Dictionary of route indices to their LP values (λ_k).
        tol: Numerical tolerance for integrality.

    Returns:
        bool: True if all fractional values are 0 or 1 AND every selected route
            (λ_k > 0.5) is strictly elementary (no cycles).
    """
    for idx, val in route_values.items():
        # Task 13: Clamp all values to [0, 1] before testing to guard against
        # slight numerical drift in Set Covering/Partitioning LP solutions.
        clamped = max(0.0, min(1.0, val))
        if abs(clamped - round(clamped)) > tol:
            return False

        # Task 16/Fix 8: Enforce elementarity in integer solutions.
        # If a variable is numerically integer (λ_k = 1.0) but represents a
        # cyclic ng-route, it is NOT a valid integer solution for the original VRPP.
        # This triggers further branching or ng-expansion.
        if clamped > 0.5:
            route = routes[idx]
            if len(set(route.nodes)) != len(route.nodes):
                return False

    # Global LP/IP consistency check.
    # A numerically binary solution in lambda-space (λ ∈ {0,1}) must also respect
    # the Set Partitioning semantics in node-space (Σ a_ik λ_k = 1 for all visited i).
    # If a node is covered by multiple columns that sum to 1.0 but have fractional
    # values, it is NOT an integer solution. If they are binary (checked above),
    # this sums to a visit count; we must ensure no node is visited more than once.
    node_usage: Dict[int, int] = {}
    for idx, val in route_values.items():
        if val > 0.5:
            for node in routes[idx].nodes:
                node_usage[node] = node_usage.get(node, 0) + 1
                if node_usage[node] > 1:
                    return False

    return True






def _select_nodes_knapsack(
    dist_matrix: np.ndarray,
    wastes: Dict[int, float],
    capacity: float,
    R: float,
    C: float,
    mandatory: Set[int],
    n_nodes: int,
    vehicle_limit: Optional[int] = None,
    target_reduction: float = 0.60,  # aim to keep ~40% of optional nodes
    time_limit: float = 10.0,
    env: Optional[Any] = None,
) -> Set[int]:
    """Select profitable optional nodes via MIP knapsack before BPC routing.

    Solves a relaxed node-selection problem: ignore routing structure,
    approximate the routing cost of each node as its average distance to
    its nearest neighbors × C, then solve a knapsack to pick the subset
    of optional nodes where marginal revenue exceeds marginal routing cost.

    This reduces the effective instance size from n to |selected| before
    the RCSPP pricing subproblem is ever called.

    Args:
        dist_matrix: Full (n+1)×(n+1) distance matrix.
        wastes: Node waste amounts.
        capacity: Vehicle capacity.
        R: Revenue per unit waste.
        C: Cost per unit distance.
        mandatory: Nodes that must be included regardless.
        n_nodes: Number of customer nodes.
        vehicle_limit: Optional vehicle limit.
        target_reduction: Target reduction in the number of nodes.
        time_limit: MIP time limit in seconds.
        env: Optional Gurobi environment.

    Returns:
        Set of selected node indices (mandatory ∪ profitable optional).
    """
    optional = [i for i in range(1, n_nodes + 1) if i not in mandatory]
    if not optional:
        return set(mandatory)

    # --- Routing cost estimate ---
    # Use Clarke-Wright savings-based approximation:
    # Cost of inserting node i into a route ≈ detour cost from its nearest
    # already-mandatory neighbor. This is tighter than average-distance.
    # For isolated optional nodes, use distance to depot × 2 as upper bound.
    depot = 0
    node_insertion_cost: Dict[int, float] = {}
    for i in optional:
        # Best insertion cost: min over all mandatory nodes j of
        #   dist(depot, i) + dist(i, j) - dist(depot, j)   (if inserting after depot)
        # Simplified: use half the round-trip cost to nearest mandatory node
        if mandatory:
            nearest_mand_dist = min(dist_matrix[i, j] for j in mandatory)
            insertion = C * (dist_matrix[depot, i] + nearest_mand_dist) / 2.0
        else:
            insertion = C * dist_matrix[depot, i]
        node_insertion_cost[i] = insertion

    # Net value: revenue minus realistic insertion cost
    node_net_value: Dict[int, float] = {}
    for i in optional:
        revenue = R * wastes.get(i, 0.0)
        node_net_value[i] = revenue - node_insertion_cost[i]

    # Pairwise synergy check: a node i might have individual insertion cost > revenue,
    # but when paired with neighbor j, the shared routing cost makes the pair profitable.
    synergistic_nodes: Set[int] = set()
    for i in optional:
        rev_i = R * wastes.get(i, 0.0)
        w_i = wastes.get(i, 0.0)
        for j in range(1, n_nodes + 1):
            if i == j:
                continue
            w_j = wastes.get(j, 0.0)
            if w_i + w_j > capacity:
                continue
            rev_pair = rev_i + (R * w_j if j in optional else 0.0)
            cost_pair = C * (dist_matrix[depot, i] + dist_matrix[i, j] + dist_matrix[j, depot])
            if rev_pair - cost_pair > 0:
                synergistic_nodes.add(i)
                break

    # Only consider nodes with positive net value or pairwise synergy
    candidates = [i for i in optional if node_net_value[i] > 0 or i in synergistic_nodes]
    if not candidates:
        return set(mandatory)

    # --- Capacity budget ---
    # Total load that can be served = vehicle_limit × capacity.
    # Subtract mandatory load to get budget for optional nodes.
    n_vehicles = (
        vehicle_limit
        if vehicle_limit is not None
        else max(2, int(np.ceil(sum(wastes.get(i, 0.0) for i in range(1, n_nodes + 1)) / capacity)))
    )
    total_capacity = n_vehicles * capacity
    mandatory_load = sum(wastes.get(i, 0.0) for i in mandatory)
    optional_budget = max(0.0, total_capacity - mandatory_load)

    # --- Hard size limit ---
    # Target at most (1 - target_reduction) × n_nodes selected nodes total,
    # floored at 20 so small-to-moderate instances are not over-reduced.
    max_optional = max(20, int(n_nodes * (1 - target_reduction)) - len(mandatory))

    try:
        m = gp.Model("node_selection", env=env) if env else gp.Model("node_selection")
        m.Params.OutputFlag = 0
        m.Params.TimeLimit = time_limit
        m.Params.MIPGap = 0.01

        y = m.addVars(candidates, vtype=GRB.BINARY, name="y")

        m.setObjective(
            gp.quicksum(node_net_value[i] * y[i] for i in candidates),
            GRB.MAXIMIZE,
        )

        # Hard capacity constraint
        m.addConstr(gp.quicksum(wastes.get(i, 0.0) * y[i] for i in candidates) <= optional_budget, name="capacity")

        # Hard size constraint — this is what was missing before
        m.addConstr(gp.quicksum(y[i] for i in candidates) <= max_optional, name="max_nodes")

        m.optimize()

        selected = set(mandatory)
        if m.SolCount > 0:
            for i in candidates:
                if y[i].X > 0.5:
                    selected.add(i)
        else:
            # Fallback: take top-k by net value
            top_k = sorted(candidates, key=lambda i: node_net_value[i], reverse=True)[:max_optional]
            selected = set(mandatory) | set(top_k)

        logger.info(
            f"[Node Selection] Knapsack selected {len(selected)} nodes "
            f"({len(selected) - len(mandatory)} optional, max_optional={max_optional}) "
            f"from {n_nodes} total. Reduced by {n_nodes - len(selected)} nodes."
        )
        return selected

    except Exception as e:
        logger.warning(f"[Node Selection] Knapsack failed ({e}), using mandatory + top-k.")
        top_k = sorted(candidates, key=lambda i: node_net_value[i], reverse=True)[:max_optional]
        return set(mandatory) | set(top_k)


def run_ms_bpc_sp(  # noqa: C901
    dist_matrix: np.ndarray,
    wastes: Dict[int, float],
    capacity: float,
    R: float,
    C: float,
    params: Optional[Union[MSBPCSPParams, Dict[str, Any]]] = None,
    mandatory_indices: Optional[Set[int]] = None,
    vehicle_limit: Optional[int] = None,
    env: Optional[Any] = None,
    node_coords: Optional[np.ndarray] = None,
    recorder: Optional[PolicyStateRecorder] = None,
    _presel_retry: bool = False,
    _keep_all_nodes: bool = False,
    **kwargs: Any,
) -> Tuple[List[List[int]], float]:
    """Solve Waste-Collecting CVRP using exact Branch-and-Price-and-Cut.

    This engine implements the Barnhart et al. (1998, OR 46(3):316-329) BPC framework with
    configurable algorithmic strategies:

    1. Initial Column Generation via greedy heuristics
    2. Branch-and-Bound tree with pluggable branching strategies
    3. Column Generation at every B&B node (following exact BPC sequencing)
    4. Exact Pricing via RCSPP
    5. Modular Valid Inequalities (RCC)
    6. Configurable search strategy (Depth-First search is preferred for basis reuse)

    Algorithm Overview:
    - Initialize B&B tree with root node and selected strategy
    - While tree is not empty:
        - Select next node using configured search strategy
        - Apply branching constraints to master and pricing
        - Run Column Generation + Cutting Plane loop (corrected sequencing)
        - If LP is integer: update incumbent
        - If LP is fractional: branch using configured branching rule
        - Prune by bound

    Args:
        dist_matrix (np.ndarray): Distance matrix (n_nodes+1 x n_nodes+1).
        wastes (Dict[int, float]): Waste volumes for each node.
        capacity (float): Vehicle capacity.
        R (float): Revenue per kg.
        C (float): Cost per km.
        params (Optional[Union[BPCParams, Dict[str, Any]]]): Configuration parameters.
        mandatory_indices (Optional[Set[int]]): Set of node indices that must be visited.
        vehicle_limit (Optional[int]): Fleet size limit.
        env (Optional[Any]): Gurobi environment (ignored, kept for compatibility).
        node_coords (Optional[np.ndarray]): Optional node coordinates for visualization.
        recorder (Optional[PolicyStateRecorder]): Optional state recorder for tracking.
        kwargs: Additional keyword arguments.

    Returns:
        Tuple[List[List[int]], float]: (Best routes found, best objective value).

    Example:
        >>> from logic.src.policies.route_construction.exact_and_decomposition_solvers.branch_and_price_and_cut.bpc_engine import run_bpc
        >>> dist_matrix = np.array([[0, 10], [10, 0]])
        >>> wastes = {1: 5.0}
        >>> routes, cost = run_bpc(dist_matrix, wastes, capacity=10, R=1, C=1)
    """
    start_time = time.perf_counter()
    n_nodes = len(dist_matrix) - 1
    m_set = mandatory_indices if mandatory_indices is not None else set()

    # Standardize params to BPCParams
    if params is None:
        params = MSBPCSPParams()
    elif isinstance(params, dict):
        params = MSBPCSPParams.from_config(params)

    # Configuration
    # Extract parameters from BPCParams
    max_cg_iter = params.max_cg_iterations
    max_cuts = params.max_cuts_per_iteration
    max_routes_per_pricing = params.max_routes_per_pricing
    max_bb_nodes = params.max_bb_nodes
    time_limit = params.time_limit
    cutting_planes_name = params.cutting_planes
    branching_strategy_name = params.branching_strategy

    # Numerical Safety Warning
    if params.rc_tolerance > params.optimality_gap:
        warnings.warn(
            f"Optimality Risk: rc_tolerance ({params.rc_tolerance}) is coarser than "
            f"optimality_gap ({params.optimality_gap}). BPC may terminate prematurely "
            f"with a sub-optimal solution.",
            stacklevel=2,
        )

    # 1. Initialize Master Problem
    # Pre-select profitable nodes via knapsack to reduce RCSPP instance size.
    # BPC then runs only on this reduced node set. On the empty-result retry
    # pass the budget is relaxed (no fleet scaling) because the capacity budget
    # assumes per-node additive value, while route-cost sharing makes value
    # non-additive: a node dropped by the budget can be half of the only
    # profitable pairing, and the BPC never sees it.
    _knapsack_budget = min(10.0, time_limit * 0.05) if time_limit > 0 else 10.0
    if _keep_all_nodes or params.exact_mode or n_nodes <= 12:
        # Exact mode, small instances, or relaxation pass: keep all nodes to prevent lossy reduction.
        selected_nodes = set(range(1, n_nodes + 1)) | set(m_set)
    else:
        selected_nodes = _select_nodes_knapsack(
            dist_matrix=dist_matrix,
            wastes=wastes,
            capacity=capacity,
            R=R,
            C=C,
            mandatory=m_set,
            n_nodes=n_nodes,
            time_limit=_knapsack_budget,
            env=env,
            vehicle_limit=None if _presel_retry else vehicle_limit,
        )

    # Build reduced problem: remap selected nodes to contiguous 1..k indices
    selected_list = sorted(selected_nodes)
    k_nodes = len(selected_list)

    # Maps: local index (1..k) ↔ original index (1..n)
    local_to_orig = {local: orig for local, orig in enumerate(selected_list, 1)}
    orig_to_local = {orig: local for local, orig in local_to_orig.items()}

    # Reduced distance matrix (k+1 × k+1), depot stays at index 0
    red_dist = np.zeros((k_nodes + 1, k_nodes + 1))
    for i_loc in range(k_nodes + 1):
        i_orig = local_to_orig.get(i_loc, 0)  # 0 → depot
        for j_loc in range(k_nodes + 1):
            j_orig = local_to_orig.get(j_loc, 0)
            red_dist[i_loc, j_orig if j_loc == 0 else orig_to_local.get(local_to_orig.get(j_loc, 0), 0)] = dist_matrix[
                i_orig, j_orig
            ]

    # Simpler: build reduced dist matrix directly
    orig_indices = [0] + selected_list  # depot + selected customers
    red_dist = dist_matrix[np.ix_(orig_indices, orig_indices)]

    red_wastes = {local: wastes.get(orig, 0.0) for local, orig in local_to_orig.items()}
    red_mandatory = {orig_to_local[i] for i in m_set if i in orig_to_local}

    master = VRPPMasterProblem(
        n_nodes=k_nodes,
        mandatory_nodes=red_mandatory,
        cost_matrix=red_dist,
        wastes=red_wastes,
        capacity=capacity,
        revenue_per_kg=R,
        cost_per_km=C,
        vehicle_limit=vehicle_limit,
    )

    # Task 3/6: Harden Ryan-Foster Exactness
    if branching_strategy_name == "ryan_foster":
        master.strict_set_partitioning = True
        logger.info("Enforcing strict Set Partitioning (SP) for Ryan-Foster branching.")

    # 2. Initial Columns — mandatory-only greedy warm-start on reduced instance
    mandatory_list = sorted(list(red_mandatory))
    if params.profit_aware_operators:
        initial_routes_nodes = greedy_profit_insertion(
            [],
            mandatory_list,
            red_dist,
            red_wastes,
            capacity,
            R=R,
            C=C,
            mandatory_nodes=mandatory_list,
            expand_pool=False,
        )
    else:
        initial_routes_nodes = greedy_insertion(
            [],
            mandatory_list,
            red_dist,
            red_wastes,
            capacity,
            mandatory_nodes=mandatory_list,
            expand_pool=False,
        )

    initial_columns = []
    pricing_solver = RCSPPSolver(
        k_nodes,
        red_dist,
        red_wastes,
        capacity,
        R,
        C,
        use_ng_routes=params.use_ng_routes,
        ng_neighborhood_size=min(params.ng_neighborhood_size, k_nodes - 1),
        node_prizes=kwargs.get("node_prizes"),
        timeout=params.rcspp_timeout,
        max_labels=params.rcspp_max_labels,
    )

    for r_nodes in initial_routes_nodes:
        route_obj = pricing_solver._compute_route_details(r_nodes)
        initial_columns.append(route_obj)

    # Seed with greedy optional-node routes so LP duals for optional nodes
    # are non-zero from the start, guiding the RCSPP toward optional nodes.
    all_local_nodes = list(range(1, k_nodes + 1))
    optional_local = [n for n in all_local_nodes if n not in red_mandatory]
    if optional_local and params.profit_aware_operators:
        try:
            opt_seed_routes = greedy_profit_insertion(
                [r for r in initial_routes_nodes],  # start from mandatory routes
                optional_local,
                red_dist,
                red_wastes,
                capacity,
                R=R,
                C=C,
                mandatory_nodes=mandatory_list,
                expand_pool=True,
            )
            for r_nodes in opt_seed_routes:
                if tuple(r_nodes) not in {tuple(r) for r in initial_routes_nodes}:
                    route_obj = pricing_solver._compute_route_details(r_nodes)
                    if route_obj.profit > 0:
                        initial_columns.append(route_obj)
            logger.info(
                f"[Warm-start] Added {len(opt_seed_routes) - len(initial_routes_nodes)} "
                f"optional-node seed routes to initial column pool."
            )
        except Exception as _e:
            logger.debug(f"[Warm-start] Optional seeding failed: {_e}")

    master.build_model(initial_columns)
    master.column_deletion_enabled = True

    # 2.1 Initialize 2-Phase Method
    # Start in Phase 1 (Feasibility) if there are mandatory nodes to cover.
    if len(red_mandatory) > 0:
        master.set_phase(1)
    else:
        master.set_phase(2)

    # 3. Initialize pricing and separation — use REDUCED instance throughout
    # pricing_solver is already initialized above on red_dist/red_wastes — reuse it.
    n_total_nodes = k_nodes + 1  # VRPPModel counts total nodes including depot (index 0)
    v_model = VRPPModel(
        n_nodes=n_total_nodes,
        cost_matrix=red_dist,
        wastes=red_wastes,
        capacity=capacity,
        revenue_per_kg=R,
        cost_per_km=C,
        mandatory_nodes=red_mandatory,
    )
    sep_engine = SeparationEngine(
        model=v_model,
        enable_heuristic_rcc_separation=params.enable_heuristic_rcc_separation,
        enable_comb_cuts=params.enable_comb_cuts,
    )

    # 4. Initialize Branch-and-Bound Tree with search strategy
    bb_tree = BranchAndBoundTree(
        v_model=v_model, params=params
    )

    # 5. Initialize cutting engine
    cut_engine = create_cutting_plane_engine(
        cutting_planes_name,
        v_model,
        sep_engine,
    )
    nodes_explored = 0
    logger.info(
        f"BPC Solver started: instance size {k_nodes} nodes "
        f"(reduced from {n_nodes} via knapsack pre-selection), "
        f"max BB nodes: {max_bb_nodes}"
    )

    # 6. Branch-and-Bound Loop
    while not bb_tree.is_empty() and nodes_explored < max_bb_nodes:
        if time_limit > 0 and (time.perf_counter() - start_time) > time_limit:
            break

        # The BBTree now internally manages the frontier priority queues (tuples vs lists).
        # We natively extract the correct node using the tree's integrated logic.
        current_node = bb_tree.get_next_node()
        if current_node is None:
            break

        nodes_explored += 1
        bb_tree.record_explored()  # Keep tree-level counter accurate

        # Remove node-local cuts from the previous node before solving this one.
        master.remove_local_cuts()

        # Get ALL branching constraints along the path from root to this node
        # (ancestors + this node). _apply_branching_to_master resets all UBs
        # to 1.0 and re-filters against the full constraint set, so it requires
        # the complete ancestor chain — not just this node's local constraint.
        branching_constraints = current_node.get_all_constraints()

        # 3. Apply branching constraints to master and pricing
        _apply_branching_to_master(master, branching_constraints, branching_strategy_name)
        if master.model:
            master.model.update()

        # Run Column Generation at this node with corrected sequencing
        # ---------------------------------------------------------------
        # Lagrangian Pre-Pruning (optional, params.lr_pre_pruning)
        # ---------------------------------------------------------------
        # Run a fast subgradient pass before expensive column generation.
        # If the Lagrangian bound is dominated by the current incumbent,
        # the node is pruned without ever calling _column_generation_loop.
        # ---------------------------------------------------------------
        if (
            params.lr_pre_pruning
            and bb_tree.best_integer_solution is not None
            and (params.lr_pre_pruning_depth_limit < 0 or current_node.depth <= params.lr_pre_pruning_depth_limit)
        ):
            # Build forced sets from branching constraints accumulated at this node.
            _lr_forced_in, _lr_forced_out = _extract_forced_sets_from_constraints(current_node.constraints)
            # Union with global mandatory for the forced_in set.
            _lr_forced_in |= m_set

            # Time budget: a small fraction of remaining solve time, capped hard.
            _remaining = time_limit - (time.perf_counter() - start_time) if time_limit > 0 else 300.0
            _lr_budget = min(
                _remaining * 0.05,  # at most 5% of remaining wall time
                params.lr_op_time_limit * params.lr_max_subgradient_iters,
            )

            if _lr_budget > 0.5:  # skip if < 0.5 s available
                _lr_ub, _lam_star, _lr_op_visited = _compute_lr_bound_at_node(
                    dist_matrix=red_dist,
                    wastes=red_wastes,
                    capacity=capacity,
                    R=R,
                    C=C,
                    mandatory=_lr_forced_in,
                    forced_out=_lr_forced_out,
                    params=params,
                    time_budget=_lr_budget,
                    env=env,
                    recorder=recorder,
                )

                _gap_threshold = bb_tree.best_integer_solution * (1.0 + params.optimality_gap)

                if _lr_ub <= _gap_threshold:
                    # LR bound is dominated — prune without CG.
                    logger.debug(
                        f"[LR Pre-Pruning] Node depth={current_node.depth} pruned. "
                        f"LR bound={_lr_ub:.4f} <= incumbent={bb_tree.best_integer_solution:.4f}."
                    )
                    if recorder:
                        recorder.record(
                            engine="bpc_lr_pre_pruning",
                            node_depth=current_node.depth,
                            lr_upper_bound=_lr_ub,
                            lam_star=_lam_star,
                            incumbent=bb_tree.best_integer_solution,
                            pruned=True,
                        )
                    bb_tree.prune_by_bound()
                    continue

                if recorder:
                    recorder.record(
                        engine="bpc_lr_pre_pruning",
                        node_depth=current_node.depth,
                        lr_upper_bound=_lr_ub,
                        lam_star=_lam_star,
                        incumbent=bb_tree.best_integer_solution,
                        pruned=False,
                    )

                # LR did not prune. Optionally seed a warm-start column into the pool.
                if params.lr_warm_start_cg and _lr_op_visited:
                    _seed_nodes = sorted(_lr_op_visited - _lr_forced_out)
                    if _seed_nodes:
                        try:
                            _seed_route = pricing_solver._compute_route_details(_seed_nodes)
                            _seed_rc = master.calculate_reduced_cost(
                                _seed_route,
                                master.get_reduced_cost_coefficients(),
                            )
                            if _seed_rc > params.rc_tolerance:
                                master.add_route(_seed_route)
                                logger.debug(
                                    f"[LR Warm-Start] Seeded column from UOP at λ*={_lam_star:.4f}, "
                                    f"rc={_seed_rc:.4f}, nodes={_seed_nodes}."
                                )
                        except Exception as _e:
                            logger.debug(f"[LR Warm-Start] Column seeding failed: {_e}. Continuing.")
        # ---------------------------------------------------------------
        # End of LR Pre-Pruning block
        # ---------------------------------------------------------------

        try:
            # Snapshot-and-restore ng-neighborhoods
            ng_snapshot = pricing_solver.save_ng_snapshot()
            try:
                _node_start = time.perf_counter()
                _elapsed_global = _node_start - start_time
                _remaining_global = max(0.1, time_limit - _elapsed_global) if time_limit > 0 else 0.0
                if _remaining_global > 0.0 and current_node.depth == 0:
                    _node_budget = min(_remaining_global, time_limit * 0.40)
                else:
                    _node_budget = _remaining_global
                lp_obj, route_values, node_final_basis, node_timed_out = _column_generation_loop(
                    master=master,
                    pricing_solver=pricing_solver,
                    cut_engine=cut_engine,
                    branching_constraints=branching_constraints,
                    max_cg_iterations=max_cg_iter,
                    max_cuts=max_cuts,
                    time_limit=_node_budget,
                    start_time=_node_start,
                    max_routes_per_pricing=max_routes_per_pricing,
                    vehicle_limit=master.vehicle_limit,
                    optimality_gap=params.optimality_gap,
                    early_termination_gap=params.early_termination_gap,
                    parent_basis=current_node.parent.lp_basis if current_node.parent else None,
                    incumbent_value=bb_tree.best_integer_solution
                    if bb_tree.best_integer_solution is not None
                    else -float("inf"),
                    node_depth=current_node.depth,
                    rc_tolerance=params.rc_tolerance,
                    cut_orthogonality_threshold=params.cut_orthogonality_threshold,
                    exact_mode=params.exact_mode,
                    cg_at_root_only=params.cg_at_root_only,
                    branching_strategy=branching_strategy_name,
                    rcspp_timeout=params.rcspp_timeout,
                )
            finally:
                # Restore ng-neighborhoods so sibling nodes are unaffected by this
                # node's dynamic ng-expansion.
                pricing_solver.restore_ng_snapshot(ng_snapshot)

            # Task 3: Global Time Limit tracking / Incomplete node handling
            if node_timed_out:
                logger.warning(
                    f"B&B node at depth {current_node.depth} timed out or incomplete. "
                    "Preserving feasible incumbent before terminating."
                )
                current_node.lp_bound = float("inf")
                if _is_solution_integer(master.routes, route_values):
                    current_node.is_integer = True
                    current_node.ip_solution = lp_obj
                    current_node.route_values = route_values
                    bb_tree.update_incumbent(current_node, lp_obj)
                else:
                    try:
                        _rem_ip = (
                            max(0.1, time_limit - (time.perf_counter() - start_time))
                            if time_limit > 0
                            else None
                        )
                        ip_obj, ip_routes = master.solve_ip(time_limit=_rem_ip)
                        if ip_obj > (
                            bb_tree.best_integer_solution
                            if bb_tree.best_integer_solution is not None
                            else -float("inf")
                        ):
                            selected_indices = {}
                            for r in ip_routes:
                                try:
                                    idx = master.routes.index(r)
                                    selected_indices[idx] = 1.0
                                except ValueError:
                                    pass
                            current_node.is_integer = True
                            current_node.ip_solution = ip_obj
                            current_node.route_values = selected_indices
                            bb_tree.update_incumbent(current_node, ip_obj)
                    except Exception as e:
                        logger.debug(f"IP solve at incomplete node failed: {e}")
                break
            current_node.lp_basis = node_final_basis
        except MSBPCSPPruningException:
            # Node provably cannot improve the incumbent — skip without marking infeasible
            continue
        except gp.GurobiError as e:
            # GurobiError (e.g. licensing, memory, degenerate model) is not a RuntimeError,
            # so it would escape the inner except and propagate to checkpoint_manager,
            # converting to CheckpointError and silently terminating the simulation.
            logger.warning(
                "GurobiError at B&B node depth=%d: %s. Marking node infeasible.",
                current_node.depth,
                e,
            )
            current_node.is_infeasible = True
            continue
        except RuntimeError as e:
            if "Conflicting must_use" in str(e):
                current_node.is_infeasible = True
                continue
            # LP infeasible at this node (regular RuntimeError)
            current_node.is_infeasible = True
            continue

        # Store LP bound
        current_node.lp_bound = lp_obj
        current_node.route_values = route_values

        # Global optimality gap check
        if bb_tree.best_integer_solution is not None:
            # Safely retrieve the best bound via the tree's statistics method,
            # which internally handles tuple unpacking and priority inversions.
            stats = bb_tree.get_statistics()
            best_open_lp_bound = stats.get("best_bound")
            if best_open_lp_bound is None:
                best_open_lp_bound = lp_obj

            # Always include the current node's LP value in the upper bound.
            global_upper_bound = max(best_open_lp_bound, lp_obj)
            # Use a stable denominator: at least 1.0, anchored to problem scale.
            denom = max(
                abs(bb_tree.best_integer_solution),
                abs(global_upper_bound),
                1.0,
            )
            global_gap = (global_upper_bound - bb_tree.best_integer_solution) / denom

            if global_gap <= params.optimality_gap:
                logger.info(f"Global optimality gap reached: {global_gap:.6f} <= {params.optimality_gap}")
                break

            # Reduced Cost Edge Fixing (Globally valid at every node)
            # We use the global_upper_bound (max of all open node bounds and current)
            # to ensure arc fixing is mathematically sound for all sibling branches.
            _apply_reduced_cost_edge_fixing(
                master=master,
                pricing_solver=pricing_solver,
                z_ub=global_upper_bound,
                z_lb=bb_tree.best_integer_solution,
            )

        # Check if solution is integer FIRST — before pruning
        if _is_solution_integer(master.routes, route_values):
            current_node.is_integer = True
            current_node.ip_solution = lp_obj

            # Update incumbent (records equal or better solutions)
            bb_tree.update_incumbent(current_node, lp_obj)
            bb_tree.prune_by_bound()

            # After recording, prune this node (no need to branch)
            continue

        # Check if we can prune by bound (strictly less than incumbent, since integer
        # solutions equal to incumbent were already handled above)
        if bb_tree.best_integer_solution is not None and lp_obj <= bb_tree.best_integer_solution:
            bb_tree.prune_by_bound()  # Ensure stale nodes are removed
            continue

        # Solution is fractional - branch
        if getattr(params, "enable_column_pool_deduplication", False):
            purged = master.deduplicate_column_pool()
            if purged > 0:
                logger.info(f"Deduplicated {purged} equivalent routes from column pool.")

        strong_candidate = None
        if getattr(params, "enable_strong_branching_heuristic", False):
            candidates = bb_tree.find_strong_branching_candidates(master.routes, route_values, max_candidates=5)
            if candidates:
                strong_candidate = _perform_strong_branching(
                    master=master,
                    candidates=candidates,
                    current_node=current_node,
                    strong_branching_size=getattr(params, "strong_branching_size", 5),
                )

        children = bb_tree.branch(
            current_node,
            master.routes,
            route_values,
            mandatory_nodes=master.mandatory_nodes,
            strong_candidate=strong_candidate,
        )

        if children is not None:
            left_child, right_child = children
            # If Ryan-Foster was selected at any level, we must harden the master to
            # strict Set Partitioning. Failure to do so allows over-covering solutions
            # to satisfy the "together" branch constraint, invalidating the bound.
            rf_used = getattr(left_child, "branching_rule", None) == "ryan_foster"
            if rf_used and not master.strict_set_partitioning:
                logger.warning(
                    "Ryan-Foster branching activated at a non-RF-primary node. "
                    "Hardening master to strict Set Partitioning for correctness."
                )
                master.strict_set_partitioning = True

        if children is None:
            # Primary branching strategy found no candidate (e.g., divergence branching
            # requires >=2 outgoing arcs at a divergence node but none exist).
            # Fall back to edge branching to avoid silently abandoning this fractional node.
            logger.warning(
                f"Primary branching strategy '{branching_strategy_name}' returned no "
                "branching candidate at a fractional node. Falling back to edge branching."
            )
            from logic.src.policies.helpers.solvers_and_matheuristics.branching import EdgeBranching

            res = EdgeBranching.find_branching_arc(master.routes, route_values)
            if res is None:
                # Truly no branching candidate — node is degenerate, skip it.
                logger.warning("Edge branching fallback also found no candidate. Skipping node.")
                continue
            (u, v), flow = res
            left_child, right_child = EdgeBranching.create_child_nodes(current_node, u, v, flow)
            children = (left_child, right_child)

        left_child, right_child = children
        use_paper_ordering = (
            getattr(params, "prefer_shorter_path_dfs", True)
            and branching_strategy_name == "divergence"
            and bb_tree.search_strategy not in ("best_first", "best-first")
        )

        if use_paper_ordering:
            # Paper §3.2: right_child (shorter path kept) explored first.
            # Push left_child first (popped last), right_child last (popped first).
            bb_tree.add_node(left_child)  # pushed first → popped last (explored second)
            bb_tree.add_node(right_child)  # pushed last  → popped first (paper §3.2)
        else:
            # LP-hint-guided ordering (non-divergence branching, or best_first mode,
            # or prefer_shorter_path_dfs=False). Explore the child with the stronger
            # LP bound first; when equal, use the child with fewer local constraints.
            hint_l = left_child.lp_bound if left_child.lp_bound is not None else -float("inf")
            hint_r = right_child.lp_bound if right_child.lp_bound is not None else -float("inf")

            if hint_l < hint_r:
                # Right child is stronger (higher bound) — push left first, right last
                bb_tree.add_node(left_child)
                bb_tree.add_node(right_child)
            elif hint_r < hint_l:
                # Left child is stronger — push right first, left last
                bb_tree.add_node(right_child)
                bb_tree.add_node(left_child)
            else:
                # Tie-break: explore child with fewer local constraints first
                # (LP closer to parent basis → better warm-start).
                if len(left_child.constraints) <= len(right_child.constraints):
                    bb_tree.add_node(right_child)  # pushed first = popped last
                    bb_tree.add_node(left_child)  # pushed last  = popped first
                else:
                    bb_tree.add_node(left_child)
                    bb_tree.add_node(right_child)

    # 6. Extract best integer solution — always proceed to Phase 3 regardless
    if bb_tree.best_integer_node is None:
        # No integer solution — use initial greedy as BPC result
        bpc_cost = 0.0
        for r_nodes in initial_routes_nodes:
            bpc_cost += pricing_solver._compute_route_details(r_nodes).profit
        bpc_routes_orig = [[local_to_orig[n] for n in r] for r in initial_routes_nodes]
    else:
        # Reconstruct solution from best node
        best_node = bb_tree.best_integer_node
        best_routes_objects = []
        for idx, val in best_node.route_values.items():  # type: ignore[union-attr]
            if val > 0.5:
                best_routes_objects.append(master.routes[idx])
        bpc_routes_orig = [[local_to_orig[n] for n in r.nodes] for r in best_routes_objects]
        bpc_cost = sum(r.profit for r in best_routes_objects)

    # ── Phase 3: Regret-2 greedy over ALL 100 nodes ───────────────────────
    # Starting from BPC routes, greedily insert every profitable unvisited
    # node. Can open new routes when existing ones are full. Near-overflow
    # bins (fill >= MAX_CAPACITY_PERCENT) are prioritised via regret boost.
    bpc_elapsed = time.perf_counter() - start_time
    remaining_budget = (time_limit if time_limit > 0 else 60.0) - bpc_elapsed
    phase3_budget = max(0.0, remaining_budget - 15.0)  # reserve 15s for phases 4+5

    final_routes: List[List[int]] = [list(r) for r in bpc_routes_orig]
    final_cost = bpc_cost
    visited_orig: Set[int] = {n for route in final_routes for n in route}

    logger.info(
        f"[Phase 3] Starting: {len(final_routes)} BPC routes, "
        f"{len(visited_orig)} visited nodes, phase3_budget={phase3_budget:.1f}s, "
        f"n_nodes={n_nodes}, m_set_size={len(m_set)}."
    )
    if phase3_budget > 0.5:
        remaining_unvisited = [i for i in range(1, n_nodes + 1) if i not in visited_orig and i not in m_set]
        # Initial sort: near-overflow first, then by revenue
        remaining_unvisited.sort(
            key=lambda i: (
                -(wastes.get(i, 0.0) / (capacity + 1e-9) >= MAX_CAPACITY_PERCENT),
                -wastes.get(i, 0.0) * R,
            )
        )

        p3_start = time.perf_counter()
        n_p3 = 0

        while remaining_unvisited and (time.perf_counter() - p3_start) < phase3_budget:
            best_regret = -float("inf")
            chosen_node, chosen_route_idx, chosen_pos, chosen_gain = -1, -1, -1, 0.0

            for node_orig in remaining_unvisited:
                waste_i = wastes.get(node_orig, 0.0)
                revenue_i = R * waste_i
                insertions: List[Tuple[float, int, int]] = []

                for r_idx, route in enumerate(final_routes):
                    if sum(wastes.get(n, 0.0) for n in route) + waste_i > capacity + 1e-6:
                        continue
                    full = [0] + route + [0]
                    for pos in range(len(full) - 1):
                        u, v = full[pos], full[pos + 1]
                        gain = revenue_i - C * (
                            dist_matrix[u, node_orig] + dist_matrix[node_orig, v] - dist_matrix[u, v]
                        )
                        insertions.append((gain, r_idx, pos))

                if vehicle_limit is None or len(final_routes) < vehicle_limit:
                    # New route option (round-trip cost)
                    new_route_gain = revenue_i - C * 2.0 * dist_matrix[0, node_orig]
                    insertions.append((new_route_gain, -1, -1))
                insertions.sort(reverse=True)
                if not insertions:
                    continue  # fleet limit reached and no route has spare capacity

                best_gain_i = insertions[0][0]
                if best_gain_i <= 0:
                    continue  # not profitable at all

                regret_i = insertions[0][0] - insertions[1][0] if len(insertions) >= 2 else float("inf")
                # Overflow bins must be inserted regardless — force priority
                fill_pct = waste_i / (capacity + 1e-9)
                if fill_pct >= MAX_CAPACITY_PERCENT:
                    regret_i += 1e6

                if regret_i > best_regret:
                    best_regret = regret_i
                    chosen_node = node_orig
                    chosen_gain = best_gain_i
                    chosen_route_idx = insertions[0][1]
                    chosen_pos = insertions[0][2]

            if chosen_node == -1:
                break  # nothing profitable left

            # Apply insertion
            if chosen_route_idx == -1:
                final_routes.append([chosen_node])
            else:
                full = [0] + final_routes[chosen_route_idx] + [0]
                final_routes[chosen_route_idx] = full[1 : chosen_pos + 1] + [chosen_node] + full[chosen_pos + 1 : -1]
            final_cost += chosen_gain
            visited_orig.add(chosen_node)
            remaining_unvisited.remove(chosen_node)
            n_p3 += 1

        logger.info(
            f"[Phase 3] Regret-2 greedy added {n_p3} nodes ({len(final_routes)} routes, profit={final_cost:.2f})."
        )
    # ── End Phase 3 ────────────────────────────────────────────────────────

    # ── Phase 5: Set Partitioning over BPC pool + Phase 3 routes ──────────
    phase5_elapsed = time.perf_counter() - start_time
    phase5_budget = max(0.0, (time_limit if time_limit > 0 else 60.0) - phase5_elapsed)

    if phase5_budget > 2.0:
        try:
            # Pool: all BPC master routes + Phase 3 routes
            pool: Dict[FrozenSet[int], Tuple[List[int], float]] = {}

            def _pool_route(nodes_orig: List[int]) -> None:
                if not nodes_orig:
                    return
                full = [0] + nodes_orig + [0]
                cost_r = sum(dist_matrix[full[i], full[i + 1]] * C for i in range(len(full) - 1))
                profit_r = sum(wastes.get(n, 0.0) * R for n in nodes_orig) - cost_r
                key = frozenset(nodes_orig)
                if key not in pool or profit_r > pool[key][1]:
                    pool[key] = (nodes_orig, profit_r)

            for r in master.routes:
                _pool_route([local_to_orig[n] for n in r.nodes])
            for route_orig in final_routes:
                _pool_route(route_orig)

            pool_list = list(pool.values())
            logger.info(f"[Phase 5] SP pool: {len(pool_list)} routes.")

            if len(pool_list) > 1:
                sp_m = gp.Model("sp_merge")
                sp_m.Params.OutputFlag = 0
                sp_m.Params.TimeLimit = min(phase5_budget, 15.0)
                sp_m.Params.MIPGap = 1e-4

                x_sp = sp_m.addVars(len(pool_list), vtype=GRB.BINARY, name="x")
                sp_m.setObjective(
                    gp.quicksum(pool_list[k][1] * x_sp[k] for k in range(len(pool_list))),
                    GRB.MAXIMIZE,
                )
                for node_orig in range(1, n_nodes + 1):
                    covers = [k for k, (rn, _) in enumerate(pool_list) if node_orig in rn]
                    if not covers:
                        continue
                    expr = gp.quicksum(x_sp[k] for k in covers)
                    if node_orig in m_set:
                        sp_m.addConstr(expr == 1)
                    else:
                        sp_m.addConstr(expr <= 1)

                # Enforce the fleet limit: the SP re-optimization must not undo the
                # limit the BPC master enforced (pool routes can exceed it when
                # Phase 3 opened extra routes or the pool mixes bounded/unbounded columns).
                if vehicle_limit is not None:
                    sp_m.addConstr(gp.quicksum(x_sp[k] for k in range(len(pool_list))) <= vehicle_limit, name="fleet_limit")

                sp_m.optimize()
                if sp_m.SolCount > 0:
                    sp_routes = [pool_list[k][0] for k in range(len(pool_list)) if x_sp[k].X > 0.5]
                    sp_profit = sum(pool_list[k][1] for k in range(len(pool_list)) if x_sp[k].X > 0.5)
                    if sp_profit > final_cost:
                        final_routes = sp_routes
                        final_cost = sp_profit
                        logger.info(f"[Phase 5] SP improved profit to {final_cost:.2f} ({len(final_routes)} routes).")
        except Exception as _e5:
            logger.warning(f"[Phase 5] SP failed: {_e5}. Using Phase 3 solution.")
    # ── End Phase 5 ────────────────────────────────────────────────────────

    # Share the original finite budget across all fallback solves. Never pass
    # zero on expiry: the solver interprets zero as an unlimited time budget.
    retry_params = params
    if time_limit > 0:
        retry_remaining = time_limit - (time.perf_counter() - start_time)
        retry_params = replace(params, time_limit=retry_remaining) if retry_remaining > 0 else None

    # Retry only fleet-constrained empty results; preserve unlimited behavior.
    if (
        not final_routes
        and k_nodes < n_nodes
        and not _presel_retry
        and vehicle_limit is not None
        and retry_params is not None
    ):
        logger.info(
            f"[Node Selection] Empty result after dropping {n_nodes - k_nodes} nodes; "
            "re-solving without the capacity budget."
        )
        return run_ms_bpc_sp(
            dist_matrix,
            wastes,
            capacity,
            R,
            C,
            params=retry_params,
            mandatory_indices=mandatory_indices,
            vehicle_limit=vehicle_limit,
            env=env,
            node_coords=node_coords,
            recorder=recorder,
            _presel_retry=True,
            **kwargs,
        )

    # Try a full-instance fleet relaxation when time remains. A returned
    # incumbent fitting the original fleet is a feasible fallback only: this
    # API returns no convergence/bound certificate, even on small instances.
    if (
        not final_routes
        and vehicle_limit is not None
        and not _keep_all_nodes
        and retry_params is not None
        and n_nodes <= _RELAX_RETRY_MAX_NODES
    ):
        fallback_routes, fallback_cost = run_ms_bpc_sp(
            dist_matrix,
            wastes,
            capacity,
            R,
            C,
            params=retry_params,
            mandatory_indices=mandatory_indices,
            vehicle_limit=None,
            env=env,
            node_coords=node_coords,
            recorder=recorder,
            _presel_retry=True,
            _keep_all_nodes=True,
            **kwargs,
        )
        if fallback_routes and len(fallback_routes) <= vehicle_limit and m_set.issubset(
            {node for route in fallback_routes for node in route}
        ):
            logger.info(
                f"[Node Selection] Unconstrained relaxation ({len(fallback_routes)} routes) "
                f"fits the fleet limit {vehicle_limit}; accepting it as a feasible fallback."
            )
            return fallback_routes, fallback_cost
        logger.info(
            "[Node Selection] Relaxation has no non-empty fleet-feasible candidate covering "
            "the mandatory nodes; keeping the fleet-constrained (empty) result."
        )

    if recorder:
        recorder.record(
            engine="exact_bpc",
            iterations=nodes_explored,
            obj_val=final_cost,
            n_routes=len(final_routes),
        )

    return final_routes, final_cost


def _apply_reduced_cost_edge_fixing(
    master: VRPPMasterProblem,
    pricing_solver: RCSPPSolver,
    z_ub: float,
    z_lb: float,
) -> int:
    """
    Applies reduced-cost variable fixing for edges.

    Fixes edge variables to zero if their reduced cost exceeds the optimality gap.

    Args:
        master: Master problem instance.
        pricing_solver: RCSPP pricing solver.
        z_ub: Current upper bound (best known solution value).
        z_lb: Current lower bound (LP relaxation value).

    Returns:
        Number of edges fixed to zero.
    """
    gap = z_ub - z_lb
    if gap <= 0:
        return 0

    dual_values = master.get_reduced_cost_coefficients()
    node_duals = dual_values.get("node_duals", {})

    fixed_count = 0
    n = pricing_solver.n_nodes + 1
    for i in range(n):
        for j in range(n):
            if i == j:
                continue

            # Exact VRPP arc reduced cost
            cost = pricing_solver.cost_matrix[i, j] * pricing_solver.C
            rev = pricing_solver.wastes.get(j, 0.0) * pricing_solver.R
            rc_ij = rev - cost - node_duals.get(j, 0.0)

            # max_path_rc integrates exact DP completion bounds (self.bounds_from / bounds_to)
            # which correctly captures all positive components of a path using edge (i, j).
            max_path_rc = pricing_solver.bounds_from[i] + rc_ij + pricing_solver.bounds_to[j]

            if z_ub + max_path_rc < z_lb - 1e-6 and (i, j) not in pricing_solver.fixed_arcs:
                # Globally fix edge
                pricing_solver.fixed_arcs.add((i, j))
                fixed_count += 1

    if fixed_count > 0:
        logger.info(
            f"[Exact Hardening] Fixed {fixed_count} edges to infinity using exact Lagrangian bounds (Gap: {gap:.4f})."
        )
    return fixed_count
