"""Route reconstruction utilities.

This module provides functions to decode predecessor matrices generated by Split
algorithms back into individual route sequences (lists of nodes).

Attributes:
    reconstruct_routes: Reconstructs routes from the predecessor matrix P.
    reconstruct_limited: Reconstructs routes for the limited vehicle split algorithm.

Example:
    >>> from logic.src.models.policies.shared.reconstruction import reconstruct_routes, reconstruct_limited
    >>> routes_batch, costs = reconstruct_routes(B, N, giant_tours, P, costs)
    >>> routes_batch, costs = reconstruct_limited(B, N, giant_tours, P_k, best_k, costs)
"""

from __future__ import annotations

from typing import List, Tuple

import torch


def reconstruct_routes(
    B: int, N: int, giant_tours: torch.Tensor, P: torch.Tensor, costs: torch.Tensor
) -> Tuple[List[List[int]], torch.Tensor]:
    """Reconstructs routes from the predecessor matrix P (unlimited vehicles).

    Backtracks from node N to node 0 using the predecessor indices to identify
    route segments in the giant tour.

    Args:
        B: Batch size.
        N: Number of customers (total nodes - 1).
        giant_tours: Node sequences of shape [B, N].
        P: Predecessor matrix of shape [B, N+1].
        costs: Total costs per batch instance of shape [B].

    Returns:
        Tuple[List[List[int]], torch.Tensor]: A tuple containing:
            - routes_batch: Nested list of identified node sequences.
            - costs: The input costs tensor, preserved for the pipeline.
    """
    routes_batch = []
    P_cpu = P.cpu().numpy()
    giant_tours_cpu = giant_tours.cpu().numpy()

    for b in range(B):
        curr = N
        route_nodes: List[int] = []
        possible = True
        while curr > 0:
            prev = P_cpu[b, curr]
            if prev == -1:
                possible = False
                break
            nodes = giant_tours_cpu[b, prev:curr]
            route_nodes = [0] + list(nodes) + route_nodes
            curr = prev

        if route_nodes and route_nodes[-1] != 0:
            route_nodes.append(0)

        if not possible:
            # Fallback or empty?
            pass

        routes_batch.append(route_nodes)
    return routes_batch, costs


def reconstruct_limited(
    B: int,
    N: int,
    giant_tours: torch.Tensor,
    P_k: torch.Tensor,
    best_k: torch.Tensor,
    costs: torch.Tensor,
) -> Tuple[List[List[int]], torch.Tensor]:
    """Reconstructs routes for the limited vehicle split algorithm.

    Backtracks through multiple layers (k) of the predecessor matrix to extract
    exactly k routes.

    Args:
        B: Batch size.
        N: Number of customers (total nodes - 1).
        giant_tours: Node sequences of shape [B, N].
        P_k: Layered predecessor matrix of shape [B, max_k + 1, N + 1].
        best_k: Optimal number of routes identified for each batch of shape [B].
        costs: Costs per batch instance of shape [B].

    Returns:
        Tuple[List[List[int]], torch.Tensor]: A tuple containing:
            - routes_batch: Nested list of identified node sequences.
            - costs: Total calculated costs tensor.
    """
    routes_batch: List[List[int]] = []
    P_cpu = P_k.cpu().numpy()
    k_cpu = best_k.cpu().numpy()
    giant_tours_cpu = giant_tours.cpu().numpy()

    for b in range(B):
        k = int(k_cpu[b])
        if k == -1 or float(costs[b].item()) == float("inf"):
            routes_batch.append([])
            continue

        curr = N
        route_nodes: List[int] = []

        # Backtrack with known k
        current_k = k

        while curr > 0 and current_k > 0:
            prev = P_cpu[b, current_k, curr]
            if prev == -1:
                break

            nodes = giant_tours_cpu[b, prev:curr]
            route_nodes = [0] + list(nodes) + route_nodes

            curr = prev
            current_k -= 1

        if route_nodes and route_nodes[-1] != 0:
            route_nodes.append(0)

        routes_batch.append(route_nodes)

    return routes_batch, costs
