"""Matrix-aware Decoder for MatNet.

This module provides the MatNetDecoder, which extends the GlimpseDecoder to
handle row and column embeddings generated by the MatNetEncoder.

Attributes:
    MatNetDecoder: Decoder refined for Matrix-based attention (MatNet).

Example:
    >>> from logic.src.models.subnets.decoders.matnet.decoder import MatNetDecoder
    >>> decoder = MatNetDecoder(embed_dim=128, hidden_dim=512, problem=atsp_env)
    >>> log_p, pi = decoder(input_tensor, embeddings, col_embeddings=col_embeddings)
"""

from __future__ import annotations

from typing import Any, Dict, Optional, Tuple, Union

import torch
from torch import nn

from logic.src.models.subnets.decoders.glimpse.decoder import GlimpseDecoder


class MatNetDecoder(GlimpseDecoder):
    """Decoder for MatNet.

    Extends GlimpseDecoder to handle row and column embeddings from MatNetEncoder,
    providing matrix-aware node selection for asymmetric or bipartite problems.

    Attributes:
        project_col_context (nn.Linear): Projection for the column-wise context.
        strategy (str): Default decoding strategy.
        temp (float): Softmax temperature for sampling.
    """

    def __init__(
        self,
        embed_dim: int,
        hidden_dim: int,
        problem: Any,
        n_heads: int = 8,
        tanh_clipping: float = 10.0,
        **kwargs: Any,
    ) -> None:
        """Initializes the MatNetDecoder.

        Args:
            embed_dim: Node embedding dimensionality.
            hidden_dim: Hidden dimension size.
            problem: Problem environment class.
            n_heads: Number of attention heads.
            tanh_clipping: Logit clipping value.
            kwargs: Additional keyword arguments.
        """
        super().__init__(
            embed_dim=embed_dim,
            hidden_dim=hidden_dim,
            problem=problem,
            n_heads=n_heads,
            tanh_clipping=tanh_clipping,
            **kwargs,
        )
        self.project_col_context = nn.Linear(embed_dim, embed_dim, bias=False)
        self.strategy = "greedy"
        self.temp = 1.0

    @property
    def device(self) -> torch.device:
        """Gets the device of the model.

        Returns:
            torch.device: Model device.
        """
        return next(self.parameters()).device

    def _precompute(self, embeddings: torch.Tensor, num_steps: int = 1) -> Any:
        """Precomputes keys and values for attention.

        Args:
            embeddings: Contextual node embeddings.
            num_steps: Unused parameter.

        Returns:
            Any: AttentionDecoderCache equivalent object.
        """
        # Standard precompute logic
        fixed = super()._precompute(embeddings, num_steps)
        return fixed

    def forward(  # type: ignore[override]
        self,
        input: Union[torch.Tensor, Dict[str, torch.Tensor]],
        embeddings: torch.Tensor,
        cost_weights: Optional[torch.Tensor] = None,
        dist_matrix: Optional[torch.Tensor] = None,
        mask: Optional[torch.Tensor] = None,
        expert_pi: Optional[torch.Tensor] = None,
        **kwargs: Any,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Matrix-aware forward pass.

        Args:
            input: Input features or state dictionary.
            embeddings: Contextual node (row) embeddings.
            cost_weights: Optional weights for costs.
            dist_matrix: Optional distance matrix.
            mask: Optional additional mask.
            expert_pi: Ground truth expert actions.
            kwargs: Additional keywords, expected to contain 'col_embeddings'.

        Returns:
            Tuple[torch.Tensor, torch.Tensor]: Log probabilities and action sequences.
        """
        col_embeddings = kwargs.get("col_embeddings")
        if col_embeddings is None:
            col_embeddings = embeddings

        state = self.problem.make_state(input, cost_weights=cost_weights)
        fixed = super()._precompute(embeddings)

        # Add column information to fixed context
        col_avg = col_embeddings.mean(1)
        fixed.graph_context = fixed.graph_context + self.project_col_context(col_avg)

        outputs = []
        sequences = []

        while not state.all_finished().all():
            get_log_p_out = self._get_log_p(fixed, state)
            if not isinstance(get_log_p_out, tuple) or len(get_log_p_out) != 2:
                # This should not happen unless _get_log_p is mocked or broken
                log_p = get_log_p_out
                mask_out = None
            else:
                log_p, mask_out = get_log_p_out

            # Use mask_out if provided, otherwise generic mask
            current_mask = mask_out if mask_out is not None else mask

            # Select node
            probs = log_p.exp()[:, 0, :]  # type: ignore[index, union-attr]
            m = current_mask[:, 0, :] if current_mask is not None else None
            selected = self._select_node(probs, m)

            state = state.update(selected)
            outputs.append(log_p[:, 0, :])  # type: ignore[index, call-overload]
            sequences.append(selected)

        if not outputs:
            return torch.zeros(state.ids.size(0), 0, embeddings.size(-1), device=embeddings.device), torch.zeros(
                state.ids.size(0), 0, dtype=torch.long, device=embeddings.device
            )

        return torch.stack(outputs, 1), torch.stack(sequences, 1)
