# @package _global_
ils_rvnd_sp:
  max_restarts: 10
  max_iter_ils: 50
  perturbation_strength: 2
  use_set_partitioning: true
  mip_time_limit: 60.0
  sp_mip_gap: 0.01
  N: 150
  A: 11.0
  MaxIter_a: 50
  MaxIter_b: 100
  MaxIterILS_b: 2000
  TDev_a: 0.05
  TDev_b: 0.005
  time_limit: 120.0
  local_search_iterations: 500
  must_go: ["other/mg_lookahead.yaml"]
  post_processing: []
