"""
Local Search Module for Route Constructors.

This module implements the GeneralLocalSearch class for refining solutions
generated by route constructors. It provides a framework for applying
various local search operators to vehicle routing solutions.

Attributes:
    GeneralLocalSearch: General-based local search implementation.

Example:
    >>> from logic.src.policies.helpers.local_search.local_search_general import GeneralLocalSearch
    >>> from logic.src.policies.wrappers.base import PolicyConfig
    >>> config = PolicyConfig()
    >>> general_ls = GeneralLocalSearch(node_coords, wastes, capacity, R, C, params)
    >>> solution = general_ls.optimize(best_solution, current_cost)
    >>> print(f"Improved cost: {solution.cost}")
"""

from typing import Any, Dict, List, Optional

import numpy as np

from .local_search_base import LocalSearch


class GeneralLocalSearch(LocalSearch):
    """General Local Search module for Route Constructors.

    Implements a full suite of local search operators to refine solutions
    generated by route constructors.

    Attributes:
        routes: The current set of routes to optimize.
        dist_matrix: Precomputed distance matrix between nodes.
        waste: Waste demand at each node.
        capacity: Vehicle capacity.
        R: Reward factor for collected waste.
        C: Cost factor for travel distance.
        neighbors: Precomputed granular neighbors for each node.
    """

    def __init__(
        self,
        dist_matrix: np.ndarray,
        waste: Dict[int, float],
        capacity: float,
        R: float,
        C: float,
        params: Any,
        neighbors: Optional[Dict[int, List[int]]] = None,
    ):
        """Initialize General Local Search.

        Args:
            dist_matrix (np.ndarray): N x N distance matrix.
            waste (Dict[int, float]): Dictionary of node waste demands.
            capacity (float): Vehicle load capacity.
            R (float): Reward factor for collected waste.
            C (float): Cost factor for travel distance.
            params (Any): Hyperparameters and configuration.
            neighbors (Optional[Dict[int, List[int]]]): Precomputed granular neighbors. Defaults to None.
        """
        super().__init__(dist_matrix, waste, capacity, R, C, params, neighbors)

    def optimize(self, solution: List[List[int]], target_neighborhood: Optional[str] = None) -> List[List[int]]:
        """Apply local search operators to the solution.

        Args:
            solution (List[List[int]]): List of routes.
            target_neighborhood (Optional[str]): If provided, only applies the specified
                neighborhood operator. Defaults to None.

        Returns:
            List[List[int]]: Optimized routes.
        """
        # Create a deep copy of routes to modify
        self.routes = [r[:] for r in solution]

        # Run optimization with optional neighborhood filter
        self._optimize_internal(target_neighborhood=target_neighborhood)

        return self.routes
