"""Set-Partitioning Polish Intensification Operator.

After thousands of ALNS or HGS iterations, the search accumulates a large
pool of individually high-quality routes that were generated but not selected
in the best-found plan.  The Set-Partitioning Polish solves the exact integer
programme that picks the optimal *combination* of routes from this pool.

Formulation (CVRP -- Set Partitioning)::

    Variables  y[k] in {0,1}  for each route k in the pool.
    Objective  Minimize Sum_k cost[k] * y[k].
    Constraints:
        Sum_k a[i,k] * y[k] = 1   for all customer i    (covered exactly once)

where a[i,k] = 1 if route k visits customer i.

Formulation (VRPP -- Set Covering / Set Partitioning)::

    Variables  y[k] in {0,1}.
    Objective  Maximize Sum_k profit[k] * y[k].
    Constraints:
        Sum_k a[i,k] * y[k] <= 1  for all customer i          (at most once)
        Sum_k a[i,k] * y[k] = 1   for all i in mandatory      (mandatory customers)

For the CVRP variant the current-solution routes are always included in the
pool to guarantee that a feasible solution exists.  For VRPP, any (possibly
empty) subset is feasible, so no such guarantee is needed.

Capacity is not explicitly re-checked here because every route in the pool
must already be capacity-feasible -- it was generated by the VRP solver under
the same capacity constraint.

Attributes:
    None

Requirements:
    Gurobi Optimizer >= 11.0 with a valid licence.

Example:
    >>> from logic.src.policies.helpers.operators.intensification import (
    ...     set_partitioning_polish, set_partitioning_polish_profit
    ... )
    >>> pool = [r for r in historical_route_pool]
    >>> polished = set_partitioning_polish(routes, pool, dist_matrix, wastes, capacity)
    >>> polished = set_partitioning_polish_profit(routes, pool, dist_matrix, wastes,
    ...                                           capacity, R=1.0, C=0.5)
"""

from typing import Dict, FrozenSet, List, Optional, Set, Tuple

import gurobipy as gp
import numpy as np
from gurobipy import GRB

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _route_cost(route: List[int], dist_matrix: np.ndarray) -> float:
    """Total travel distance of *route* (depot-inclusive round trip).

    Args:
        route: List of customer node IDs (depot implicit at index 0).
        dist_matrix: Square distance matrix with depot at index 0.

    Returns:
        Total route distance as a float.
    """
    if not route:
        return 0.0
    cost = float(dist_matrix[0, route[0]])
    for k in range(len(route) - 1):
        cost += float(dist_matrix[route[k], route[k + 1]])
    cost += float(dist_matrix[route[-1], 0])
    return cost


def _route_profit(
    route: List[int],
    dist_matrix: np.ndarray,
    wastes: Dict[int, float],
    R: float,
    C: float,
) -> float:
    """Net profit of *route*: revenue minus C times distance.

    Args:
        route: List of customer node IDs.
        dist_matrix: Square distance matrix with depot at index 0.
        wastes: Node demand lookup used to compute revenue.
        R: Revenue per unit waste.
        C: Cost per unit distance.

    Returns:
        Net profit as a float.
    """
    revenue = sum(wastes.get(n, 0.0) for n in route) * R
    return revenue - _route_cost(route, dist_matrix) * C


def _deduplicate_pool(
    route_pool: List[List[int]],
) -> List[List[int]]:
    """Remove exact duplicate routes (same sequence of nodes).

    Args:
        route_pool: List of routes, where each route is a list of node IDs.

    Returns:
        List[List[int]]: Deduplicated list preserving first-occurrence order.
    """
    seen: Set[Tuple[int, ...]] = set()
    unique: List[List[int]] = []
    for route in route_pool:
        key = tuple(route)
        if key not in seen:
            seen.add(key)
            unique.append(route)
    return unique


# ---------------------------------------------------------------------------
# Public API — CVRP
# ---------------------------------------------------------------------------


def set_partitioning_polish(  # noqa: C901
    routes: List[List[int]],
    route_pool: List[List[int]],
    dist_matrix: np.ndarray,
    wastes: Dict[int, float],
    capacity: float,
    time_limit: float = 60.0,
    seed: int = 42,
) -> List[List[int]]:
    """Find the minimum-cost combination of pool routes covering all customers.

    Builds an exact Set-Partitioning MIP over the route pool and solves it
    with Gurobi.  Each customer must appear in exactly one selected route.

    The current *routes* are merged into the pool before solving to guarantee
    feasibility.  Duplicate routes are removed.  If the model finds no integer
    solution within *time_limit*, the original *routes* are returned unchanged.

    Args:
        routes: Current best plan.  Its routes are added to the pool to ensure
            the original solution is always feasible as a starting point.
        route_pool: Pool of previously generated capacity-feasible routes.
            Each element is a list of customer node IDs (depot implicit).
        dist_matrix: Square distance matrix ``(N+1, N+1)``, depot at index 0.
        wastes: Node demand lookup (unused here; included for API consistency).
        capacity: Maximum vehicle load (all pool routes assumed feasible).
        time_limit: Gurobi time limit in seconds.  Default 60.
        seed: Gurobi random seed.

    Returns:
        List[List[int]]: Selected routes that together cover every customer
            at minimum total distance.  Falls back to *routes* if Gurobi finds
            no feasible integer solution.

    Example:
        >>> polished = set_partitioning_polish(routes, pool, dist_matrix,
        ...                                    wastes, capacity)
    """
    # Merge current solution into pool for guaranteed feasibility
    combined = list(routes) + list(route_pool)
    pool = _deduplicate_pool([r for r in combined if r])

    if not pool:
        return [list(r) for r in routes if r]

    # Identify all customers that must be covered
    all_customers: Set[int] = {n for r in routes for n in r}
    if not all_customers:
        return []

    # Build coverage matrix: customers → list of (pool_idx, pool route)
    customers = sorted(all_customers)
    n_routes = len(pool)

    # a[k][i] = 1 if pool route k covers customer i
    # Store as sets for fast lookup
    coverage: List[FrozenSet[int]] = [frozenset(r) for r in pool]
    costs = [_route_cost(r, dist_matrix) for r in pool]

    m = gp.Model("sp_polish_cvrp")
    m.setParam("OutputFlag", 0)
    m.setParam("TimeLimit", time_limit)
    m.setParam("Seed", seed)
    m.setParam("MIPGap", 1e-4)
    m.setParam("LogToConsole", 0)

    y = [m.addVar(vtype=GRB.BINARY, name=f"y_{k}") for k in range(n_routes)]
    m.update()

    # Objective: minimise total route cost
    m.setObjective(gp.quicksum(costs[k] * y[k] for k in range(n_routes)), GRB.MINIMIZE)

    # Covering constraints: each customer covered exactly once
    for cust in customers:
        covering = [k for k in range(n_routes) if cust in coverage[k]]
        if not covering:
            # This customer is uncoverable — return original plan
            return [list(r) for r in routes if r]
        m.addConstr(gp.quicksum(y[k] for k in covering) == 1, name=f"cover_{cust}")

    m.optimize()

    if m.Status not in (GRB.OPTIMAL, GRB.SUBOPTIMAL, GRB.TIME_LIMIT) or m.SolCount == 0:
        return [list(r) for r in routes if r]

    selected = [pool[k] for k in range(n_routes) if y[k].X > 0.5]
    return [list(r) for r in selected if r]


# ---------------------------------------------------------------------------
# Public API — VRPP
# ---------------------------------------------------------------------------


def set_partitioning_polish_profit(  # noqa: C901
    routes: List[List[int]],
    route_pool: List[List[int]],
    dist_matrix: np.ndarray,
    wastes: Dict[int, float],
    capacity: float,
    R: float,
    C: float,
    mandatory_nodes: Optional[List[int]] = None,
    time_limit: float = 60.0,
    seed: int = 42,
) -> List[List[int]]:
    """Find the maximum-profit subset of pool routes covering mandatory customers.

    VRPP adaptation of :func:`set_partitioning_polish`.  Customers are optional
    (each may be covered by at most one selected route), except those in
    *mandatory_nodes* which must be covered by exactly one route.  The solver
    maximises the total route profit across selected routes.

    A route's profit is computed as:
        profit = Σ_{i ∈ route} waste[i] · R − cost · C

    Unprofitable routes (negative profit) can be excluded by the solver unless
    they contain mandatory customers.

    Args:
        routes: Current best plan.  Included in the pool for reference; the
            solver is not required to select any of these routes.
        route_pool: Pool of previously generated capacity-feasible routes.
        dist_matrix: Distance matrix (depot at index 0).
        wastes: Node demand lookup.
        capacity: Vehicle capacity (all pool routes assumed feasible).
        R: Revenue per unit waste.
        C: Cost per unit distance.
        mandatory_nodes: Customers that must appear in the final solution.
        time_limit: Gurobi time limit in seconds.  Default 60.
        seed: Gurobi random seed.

    Returns:
        List[List[int]]: Selected routes maximising total profit subject to
            each customer appearing at most once.  Falls back to *routes* if
            Gurobi finds no feasible integer solution.

    Example:
        >>> polished = set_partitioning_polish_profit(
        ...     routes, pool, dist_matrix, wastes, capacity, R=1.0, C=0.5
        ... )
    """
    mandatory: Set[int] = set(mandatory_nodes) if mandatory_nodes else set()

    combined = list(routes) + list(route_pool)
    pool = _deduplicate_pool([r for r in combined if r])

    if not pool:
        return [list(r) for r in routes if r]

    all_customers: Set[int] = {n for r in pool for n in r}
    n_routes = len(pool)

    coverage: List[FrozenSet[int]] = [frozenset(r) for r in pool]
    profits = [_route_profit(r, dist_matrix, wastes, R, C) for r in pool]

    m = gp.Model("sp_polish_vrpp")
    m.setParam("OutputFlag", 0)
    m.setParam("TimeLimit", time_limit)
    m.setParam("Seed", seed)
    m.setParam("MIPGap", 1e-4)

    y = [m.addVar(vtype=GRB.BINARY, name=f"y_{k}") for k in range(n_routes)]
    m.update()

    # Objective: maximise total profit
    m.setObjective(gp.quicksum(profits[k] * y[k] for k in range(n_routes)), GRB.MAXIMIZE)

    # At-most-once covering constraint for every customer
    for cust in all_customers:
        covering = [k for k in range(n_routes) if cust in coverage[k]]
        if covering:
            m.addConstr(gp.quicksum(y[k] for k in covering) <= 1, name=f"atmost_{cust}")

    # Exactly-once covering for mandatory customers
    for cust in mandatory:
        covering = [k for k in range(n_routes) if cust in coverage[k]]
        if covering:
            m.addConstr(gp.quicksum(y[k] for k in covering) == 1, name=f"must_{cust}")
        # If no pool route covers a mandatory customer, add a singleton fallback
        else:
            pool.append([cust])
            profits.append(_route_profit([cust], dist_matrix, wastes, R, C))
            coverage.append(frozenset([cust]))
            new_var = m.addVar(vtype=GRB.BINARY, name=f"y_{len(pool) - 1}")
            m.addConstr(new_var == 1, name=f"must_fallback_{cust}")
            y.append(new_var)
            n_routes += 1
            m.update()

    m.optimize()

    if m.Status not in (GRB.OPTIMAL, GRB.SUBOPTIMAL, GRB.TIME_LIMIT) or m.SolCount == 0:
        return [list(r) for r in routes if r]

    selected = [pool[k] for k in range(len(y)) if y[k].X > 0.5]
    return [list(r) for r in selected if r]
