r"""
Integer L-Shaped (Benders Decomposition) Policy Adapter for Stochastic VRPP.

Adapts the Benders decomposition engine to the Multi-Period Stochastic framework,
handling parameter mapping, recourse evaluation, and non-anticipativity
enforcement within a rolling-horizon context.

Algorithm — Integer L-Shaped Method (Laporte & Louveaux, 1993):
    The problem is formulated as a Two-Stage Stochastic Integer Program (2-SIP):

    1. **Stage 1 (Master Problem)**:
       Binary routing arcs $x_{ij}$ and node-visit flags $y_i$ are decided
       for Day 1 before stochastic demand is revealed. A surrogate variable $\theta$
       approximates the expected recourse cost for the remaining $T-1$ days.

    2. **Stage 2 (Recourse Subproblem)**:
       Evaluates the expected penalty $Q(\mathbf{y})$ incurred by the Stage 1
       decisions across all scenarios in the `ScenarioTree`. This includes
       cumulative overflow penalties and missed revenue over the $T$-day horizon.

Iterative Process:
    - **Optimality Cuts**: If the surrogate $\theta$ is less than the true
      expected recourse $Q(\mathbf{y})$, an L-shaped optimality cut is added to
      the master problem.
    - **Combinatorial Cuts**: Since Stage 1 variables are binary, the engine
      generates powerful combinatorial cuts that are valid for all integer
       solutions, accelerating convergence compared to standard Benders.

Implementation:
    - **Lookahead**: Uses the `ScenarioTree` to compute analytical recourse gradients.
    - **Rolling Horizon**: Re-solves the Master Problem each day, updating $\theta$
      based on latest inventory observations.

Registry key: ``"ils_bd"``

References:
    Laporte, G., & Louveaux, F. V. (1993). "The integer L-shaped method for
    stochastic integer programs with complete recourse". Operations Research
    Letters, 13(3), 133-142.
"""

from dataclasses import asdict
from typing import Any, Dict, List, Optional, Tuple, Type, Union

import numpy as np

from logic.src.configs.policies import IntegerLShapedBendersConfig
from logic.src.policies.helpers.branching_solvers.vrpp_model import VRPPModel
from logic.src.policies.route_construction.base.base_multi_period_policy import BaseMultiPeriodRoutingPolicy
from logic.src.policies.route_construction.base.factory import RouteConstructorRegistry

from .ils_bd_engine import IntegerLShapedEngine
from .params import ILSBDParams


@RouteConstructorRegistry.register("ils_bd")
class IntegerLShapedPolicy(BaseMultiPeriodRoutingPolicy):
    r"""Integer L-Shaped (Benders Decomposition) policy for multi-period planning.
    Standardized to the Multi-Period framework with stochastic lookahead.
    """

    def __init__(
        self,
        config: Optional[Union[IntegerLShapedBendersConfig, Dict[str, Any]]] = None,
    ) -> None:
        """Initialise the ILS policy adapter."""
        super().__init__(config)

    @classmethod
    def _config_class(cls) -> Type[IntegerLShapedBendersConfig]:
        """Return the typed configuration class."""
        return IntegerLShapedBendersConfig

    def _get_config_key(self) -> str:
        """Return the YAML config key."""
        return "ils_bd"

    def _run_multi_period_solver(
        self,
        tree: Any,
        capacity: float,
        revenue: float,
        cost_unit: float,
        **kwargs: Any,
    ) -> Tuple[List[List[List[int]]], float, Dict[str, Any]]:
        """
        Execute the Integer L-Shaped Benders Decomposition solver logic.

        This method optimizes Stage 1 decisions (Day 0 routes) by evaluating the
        analytical expected recourse cost across all scenarios in the
        `ScenarioTree`. It iteratively solves a Master Problem and injects
        optimality and feasibility cuts generated by the Stage 2 sub-problems
        until the first-stage decisions are stable and consistent with the
        expected cumulative profit over the $T$-period horizon.

        Args:
            tree (ScenarioTree): Tree of future fill rate realization scenarios.
            capacity (float): Maximum vehicle collection capacity.
            revenue (float): Revenue obtained per kilogram of waste collected.
            cost_unit (float): Monetary cost incurred per kilometer traveled.
            **kwargs: Additional context, including:
                - distance_matrix (np.ndarray): Symmetric distance matrix.
                - sub_wastes (Dict[int, float]): Current bin fill levels.
                - mandatory (List[int]): Bins that MUST be collected today.

        Returns:
            Tuple[List[List[List[int]]], float, Dict[str, Any]]:
                A 3-tuple containing:
                - full_plan: Collection plan (nested list by day and vehicle).
                - expected_profit: Optimal objective value (expected total net profit).
                - metadata: Execution statistics, including the number of Benders cuts.
        """
        sub_dist_matrix = kwargs["distance_matrix"]
        sub_wastes = kwargs.get("sub_wastes", {})
        mandatory_nodes = kwargs.get("mandatory", [])

        n_nodes = len(sub_dist_matrix)
        vrpp_model = VRPPModel(
            n_nodes=n_nodes,
            cost_matrix=sub_dist_matrix,
            wastes=sub_wastes,  # Day 0 observed
            capacity=capacity,
            revenue_per_kg=revenue,
            cost_per_km=cost_unit,
            mandatory_nodes=set(mandatory_nodes),
        )

        # Merge config
        params = ILSBDParams.from_config(asdict(self.config))

        # Invoke Multi-Period Engine
        engine = IntegerLShapedEngine(model=vrpp_model, params=params)
        routes, _y_hat, profit, stats = engine.solve(tree=tree)

        # Build T-period plan snapshot
        # For ILS-BD, we currently extract the first-stage route.
        # Future days are handled as expected recourse.
        full_plan: List[List[List[int]]] = [[] for _ in range(self.horizon + 1)]
        full_plan[0] = routes

        return full_plan, profit, stats

    def _run_solver(
        self,
        sub_dist_matrix: np.ndarray,
        sub_wastes: Dict[int, float],
        capacity: float,
        revenue: float,
        cost_unit: float,
        values: Dict[str, Any],
        mandatory_nodes: List[int],
        **kwargs: Any,
    ) -> Tuple[List[List[int]], float, float]:
        """Legacy fallback."""
        return [], 0.0, 0.0
