# File System Settings
OPERATION_MAP = {
    "": "",
    "Set value (=)": "=",
    "Compare equality (==)": "==",
    "Compare inequality (!=)": "!=",
    "Add value (+)": "+",
    "Subtract value (-)": "-",
    "Multiply by value (*)": "*",
    "Divide by value (/)": "/",
    "Power of value (**)": "**",
    "Floor division by value (//)": "//",
    "Modulo operation (%)": "%",
    "Shift left (<<)": "<<",
    "Check if smaller (<)": "<",
    "Check if smaller or equal (<=)": "<=",
    "Shift right (>>)": ">>",
    "Check if larger (>)": ">",
    "Check if larger or equal (>=)": ">=",
    "Perform bit-wise OR (|)": "|",
    "Perform bit-wise AND (&)": "&",
    "Perform bit-wise XOR (^)": "^",
    "Check if value is new_value (is)": "is",
    "Check if value is not new_value (is not)": "isnot",
    "Check if value is in new_value (in)": "in",
    "Check if value is not in new_value (not in)": "notin",
    "Matrix multiplication (@)": "@",
    "Division with remainder (divmod - returns tuple)": "divmod",
}

FUNCTION_MAP = {
    "Mean": "mean",
    "Standard Deviation (stdev)": "stdev",
    "Median": "median",
    "Mode": "mode",
    "Variance (var)": "var",
    "Quantiles (quant)": "quant",
    "Size": "size",
    "Summmation (sum)": "sum",
    "Minimum (min)": "min",
    "Maximum (max)": "max",
}
