r"""
Branch-and-Price-and-Cut (BPC) Engine for VRPP.

This engine implements a state-of-the-art exact solver for the Vehicle Routing
Problem with Profits (VRPP), adapting the macro-architectural sequencing
framework of Barnhart, Hane, and Vance (2000) ["BHV2000"] to modern routing
heuristics and the Set Partitioning (SP) master formulation.

Paper-to-Implementation Mapping (BHV2000)
==========================================

§2 – ODIMCF Formulation → VRPP Set Partitioning
    Paper formulates arc-based multi-commodity flow (ODIMCF); this engine
    uses an equivalent column-based Set Partitioning Problem (SPP) over
    route variables λ_k.  Customer coverage constraints replace O-D flow
    conservation; the arc-capacity knapsack structure underpins LCI cuts.
    See: ``VRPPMasterProblem`` in master_problem.py.

§3 – Column Generation / Restricted Master Problem (RMP)
    LP relaxation of the SPP is solved iteratively.  New columns (routes)
    are generated by the RCSPP pricing subproblem (see §3.2 below).
    Phase I (Farkas pricing) guarantees initial LP feasibility without Big-M.
    Phase II switches to profit-maximising pricing once feasibility holds.
    Implementation: ``_column_generation_loop``, ``_solve_farkas_pricing_step``,
    ``_solve_pricing_step``.

§3.2 – Pricing Subproblem (RCSPP)
    Paper uses a shortest-path labelling algorithm on a time-space network.
    This engine uses a label-correcting DP with ng-route relaxation
    (Baldacci et al. 2011) to avoid the worst-case exponential state space.
    Reduced-cost formula: c'_k = c_k − Σ_i π_i δ_ik − Σ π_S · a_Sk
                                      − Σ γ_{lm} · α_{lm}^k  (LCI §4.2)
    Implementation: ``RCSPPSolver`` / ``_label_correcting_algorithm`` in
    rcspp_dp.py.

§4.1 – Lifted Cover Inequalities (LCI)
    Arc-capacity knapsack cuts lifted via the Gu, Nemhauser, Savelsbergh
    (1995a) exact sequence-independent procedure.  Both the physical-capacity
    engine (PhysicalCapacityLCIEngine) and the saturated-arc engine
    (SaturatedArcLCIEngine) are implemented; the latter matches §6 exactly.
    LCI duals γ_{lm} modify pricing arc costs as c'_{lm}^k = c_{lm}^k + γ_{lm}·α_{lm}^k.
    Implementation: cutting_planes.py; dual integration: rcspp_dp.py:
    ``_extend_label``.

§4.2 – LCI Dual Integration in Pricing
    Per-node α lifting coefficients are archived in the GlobalCutPool and
    re-injected at descendant B&B nodes via ``apply_to_master``.  The
    composite dual dict emitted by ``get_reduced_cost_coefficients`` includes
    ``lci_duals`` and ``lci_node_alphas`` keys, which flow through to the
    label-extension step.
    Implementation: master_problem.py: ``get_reduced_cost_coefficients``;
    rcspp_dp.py: ``solve`` → ``_label_correcting_algorithm`` → ``_extend_label``.

§4.3 – Divergence Node Branching
    Two highest-λ fractional routes are traced step-by-step from the depot.
    The first node where they diverge is the branching node d.  arc_set_1
    contains the arc of the *shorter* path (path p in the paper); arc_set_2
    contains the remaining outgoing arcs including the longer path's arc.
    strategies.py swaps arc_p1/arc_p2 when path1 is longer, ensuring nxt_p1
    (shorter path's arc) heads the flow-sorted list and lands in arc_set_1.
    left_child  forbids arc_set_1 → longer path kept  (Paper's Child 1).
    right_child forbids arc_set_2 → shorter path kept (Paper's Child 2,
    explored FIRST per §3.2: "we choose the side where A(d,a2) is forbidden").
    Falls back to aggregate-flow heuristic when no common prefix exists.
    Implementation: ``MultiEdgePartitionBranching.find_divergence_node``
    in branching.py.

§5 – DFS Node Selection
    The B&B tree uses Depth-First Search (``DepthFirstStrategy``) to maximise
    LP basis reuse across parent → child transitions.  A warm-start snapshot
    of the parent's LP basis is stored in ``BranchNode.lp_basis`` and
    restored via ``master.restore_basis`` at the start of each child's CG loop.
    Implementation: ``search_strategy.py``, ``BranchAndBoundTree.add_node``,
    ``_column_generation_loop`` (``parent_basis`` arg).

§6 – Saturated-Arc LCI Separation
    For each arc (i,j) with fractional flow > 1 − ε, the set of routes using
    that arc forms a cover; the basic cover inequality is lifted and added.
    Implementation: ``SaturatedArcLCIEngine`` in cutting_planes.py.

Table 2 – CG at Root Only
    Set ``BPCParams.cg_at_root_only = True`` to replicate the Table 2
    experiment: column generation is skipped at all non-root nodes; only
    the pool built at the root is sifted and the LP re-solved.
    Implementation: ``_column_generation_loop`` (``cg_at_root_only`` arg).

Additional components not in BHV2000 (VRPP adaptations):
    - Ryan-Foster (1981) node-pair branching for the SPP.
    - Rounded Capacity Cuts (RCC, Lysgaard et al. 2004).
    - Subset-Row Inequalities (3-SRI, Jepsen et al. 2008).
    - Dual smoothing (Wentges 1997) for faster CG convergence.
    - GlobalCutPool: centralised cut registry ensuring parent cuts are
      re-injected at all descendant B&B nodes.

Attributes:
    logger (logging.Logger): Module-level logger.
    _FARKAS_TOL (float): Numerical tolerance for Farkas pricing.

Example:
    >>> from logic.src.policies.route_construction.exact_and_decomposition_solvers.branch_and_price_and_cut.bpc_engine import run_bpc
    >>> dist_matrix = np.array([[0, 10], [10, 0]])
    >>> wastes = {1: 5.0}
    >>> routes, cost = run_bpc(dist_matrix, wastes, capacity=10, R=1, C=1)

References:
-----------
- Barnhart, C., Hane, C. A., & Vance, P. H. (2000). "Using branch-and-price-and-cut
  to solve origin-destination integer multicommodity flow problems."
  Operations Research, 48(2), 318–326.
- Barnhart, C., et al. (1998). "Branch-and-price: Column generation for solving
  huge integer programs." Operations Research, 46(3), 316–329.
- Baldacci, R., et al. (2011). "New state-space relaxation for the car-dependent VRP."
- Ryan, D. M., & Foster, B. A. (1981). "An integer programming approach to scheduling."
- Lysgaard, J., et al. (2004). "A new branch-and-cut algorithm for the capacitated VRP."
- Jepsen, M., et al. (2008). "Subset-row inequalities applied to the VRP with time windows."
- Gu, Z., Nemhauser, G. L., & Savelsbergh, M. W. P. (1995a). "Lifted cover inequalities
  for 0-1 integer programs."
- Wentges, P. (1997). "Weighted Dantzig-Wolfe decomposition for linear mixed-integer programming."
"""

import logging
import time
import warnings
from typing import Any, Dict, List, Optional, Set, Tuple, Union

import gurobipy as gp
import numpy as np
from gurobipy import GRB

from logic.src.policies.helpers.operators.recreate_repair.greedy import greedy_insertion, greedy_profit_insertion
from logic.src.policies.helpers.solvers_and_matheuristics import (
    BranchAndBoundTree,
    RCSPPSolver,
    SeparationEngine,
    VRPPMasterProblem,
)
from logic.src.policies.helpers.solvers_and_matheuristics.search.cutting_planes import (
    create_cutting_plane_engine,
)
from logic.src.policies.helpers.solvers_and_matheuristics.vrpp_model import VRPPModel
from logic.src.tracking.viz_mixin import PolicyStateRecorder

from .bpc_utils import (
    BPCPruningException,
)
from .bpc_utils import (
    apply_branching_to_master as _apply_branching_to_master,
)
from .bpc_utils import (
    apply_reduced_cost_edge_fixing as _apply_reduced_cost_edge_fixing,
)
from .bpc_utils import (
    column_generation_loop as _column_generation_loop,
)
from .bpc_utils import (
    compute_lr_bound_at_node as _compute_lr_bound_at_node,
)
from .bpc_utils import (
    extract_forced_sets_from_constraints as _extract_forced_sets_from_constraints,
)
from .bpc_utils import (
    is_solution_integer as _is_solution_integer,
)
from .bpc_utils import (
    perform_strong_branching as _perform_strong_branching,
)
from .bpc_utils import (
    reduced_cost_arc_fixing as _reduced_cost_arc_fixing,
)
from .params import BPCParams

logger = logging.getLogger(__name__)

# Minimum Farkas dual-ray weight to accept a column in Phase I pricing.
# Columns with weight below this threshold do not meaningfully contribute
# toward restoring LP feasibility and are discarded.
_FARKAS_TOL: float = 1e-6


# BPCPruningException → imported from .bpc_utils.branching_utils


def _select_nodes_knapsack(
    dist_matrix: np.ndarray,
    wastes: Dict[int, float],
    capacity: float,
    R: float,
    C: float,
    mandatory: Set[int],
    n_nodes: int,
    vehicle_limit: Optional[int] = None,
    target_reduction: float = 0.60,  # aim to keep ~40% of optional nodes
    time_limit: float = 10.0,
    env: Optional[Any] = None,
) -> Set[int]:
    """Select profitable optional nodes via MIP knapsack before BPC routing.

    Solves a relaxed node-selection problem: ignore routing structure,
    approximate the routing cost of each node as its average distance to
    its nearest neighbors × C, then solve a knapsack to pick the subset
    of optional nodes where marginal revenue exceeds marginal routing cost.

    This reduces the effective instance size from n to |selected| before
    the RCSPP pricing subproblem is ever called.

    Args:
        dist_matrix: Full (n+1)×(n+1) distance matrix.
        wastes: Node waste amounts.
        capacity: Vehicle capacity.
        R: Revenue per unit waste.
        C: Cost per unit distance.
        mandatory: Nodes that must be included regardless.
        n_nodes: Number of customer nodes.
        vehicle_limit: Optional vehicle limit.
        target_reduction: Target reduction in number of optional nodes.
        time_limit: MIP time limit in seconds.
        env: Optional Gurobi environment.

    Returns:
        Set of selected node indices (mandatory ∪ profitable optional).
    """
    optional = [i for i in range(1, n_nodes + 1) if i not in mandatory]
    if not optional:
        return set(mandatory)

    # --- Routing cost estimate ---
    # Use Clarke-Wright savings-based approximation:
    # Cost of inserting node i into a route ≈ detour cost from its nearest
    # already-mandatory neighbor. This is tighter than average-distance.
    # For isolated optional nodes, use distance to depot × 2 as upper bound.
    depot = 0
    node_insertion_cost: Dict[int, float] = {}
    for i in optional:
        # Best insertion cost: min over all mandatory nodes j of
        #   dist(depot, i) + dist(i, j) - dist(depot, j)   (if inserting after depot)
        # Simplified: use half the round-trip cost to nearest mandatory node
        if mandatory:
            nearest_mand_dist = min(dist_matrix[i, j] for j in mandatory)
            insertion = C * (dist_matrix[depot, i] + nearest_mand_dist) / 2.0
        else:
            insertion = C * dist_matrix[depot, i]
        node_insertion_cost[i] = insertion

    # Net value: revenue minus realistic insertion cost
    node_net_value: Dict[int, float] = {}
    for i in optional:
        revenue = R * wastes.get(i, 0.0)
        node_net_value[i] = revenue - node_insertion_cost[i]

    # Only consider nodes with positive net value
    candidates = [i for i in optional if node_net_value[i] > 0]
    if not candidates:
        return set(mandatory)

    # --- Capacity budget ---
    # Total load that can be served = vehicle_limit × capacity.
    # Subtract mandatory load to get budget for optional nodes.
    n_vehicles = (
        vehicle_limit
        if vehicle_limit is not None
        else max(2, int(np.ceil(sum(wastes.get(i, 0.0) for i in range(1, n_nodes + 1)) / capacity)))
    )
    total_capacity = n_vehicles * capacity
    mandatory_load = sum(wastes.get(i, 0.0) for i in mandatory)
    optional_budget = max(0.0, total_capacity - mandatory_load)

    # --- Hard size limit ---
    # Target at most (1 - target_reduction) × n_nodes selected nodes total,
    # so RCSPP gets an instance small enough to solve in rcspp_timeout.
    max_optional = max(5, int(n_nodes * (1 - target_reduction)) - len(mandatory))

    try:
        m = gp.Model("node_selection", env=env) if env else gp.Model("node_selection")
        m.Params.OutputFlag = 0
        m.Params.TimeLimit = time_limit
        m.Params.MIPGap = 0.01

        y = m.addVars(candidates, vtype=GRB.BINARY, name="y")

        m.setObjective(
            gp.quicksum(node_net_value[i] * y[i] for i in candidates),
            GRB.MAXIMIZE,
        )

        # Hard capacity constraint
        m.addConstr(gp.quicksum(wastes.get(i, 0.0) * y[i] for i in candidates) <= optional_budget, name="capacity")

        # Hard size constraint — this is what was missing before
        m.addConstr(gp.quicksum(y[i] for i in candidates) <= max_optional, name="max_nodes")

        m.optimize()

        selected = set(mandatory)
        if m.SolCount > 0:
            for i in candidates:
                if y[i].X > 0.5:
                    selected.add(i)
        else:
            # Fallback: take top-k by net value
            top_k = sorted(candidates, key=lambda i: node_net_value[i], reverse=True)[:max_optional]
            selected = set(mandatory) | set(top_k)

        logger.info(
            f"[Node Selection] Knapsack selected {len(selected)} nodes "
            f"({len(selected) - len(mandatory)} optional, max_optional={max_optional}) "
            f"from {n_nodes} total. Reduced by {n_nodes - len(selected)} nodes."
        )
        return selected

    except Exception as e:
        logger.warning(f"[Node Selection] Knapsack failed ({e}), using mandatory + top-k.")
        top_k = sorted(candidates, key=lambda i: node_net_value[i], reverse=True)[:max_optional]
        return set(mandatory) | set(top_k)


def run_bpc(  # noqa: C901
    dist_matrix: np.ndarray,
    wastes: Dict[int, float],
    capacity: float,
    R: float,
    C: float,
    params: Optional[Union[BPCParams, Dict[str, Any]]] = None,
    mandatory_indices: Optional[Set[int]] = None,
    vehicle_limit: Optional[int] = None,
    env: Optional[Any] = None,
    node_coords: Optional[np.ndarray] = None,
    recorder: Optional[PolicyStateRecorder] = None,
    **kwargs: Any,
) -> Tuple[List[List[int]], float]:
    """Solve Waste-Collecting CVRP using exact Branch-and-Price-and-Cut.

    This engine implements the Barnhart et al. (1998, OR 46(3):316-329) BPC framework with
    configurable algorithmic strategies:

    1. Initial Column Generation via greedy heuristics
    2. Branch-and-Bound tree with pluggable branching strategies
    3. Column Generation at every B&B node (following exact BPC sequencing)
    4. Exact Pricing via RCSPP
    5. Modular Valid Inequalities (RCC)
    6. Configurable search strategy (Depth-First search is preferred for basis reuse)

    Algorithm Overview:
    - Initialize B&B tree with root node and selected strategy
    - While tree is not empty:
        - Select next node using configured search strategy
        - Apply branching constraints to master and pricing
        - Run Column Generation + Cutting Plane loop (corrected sequencing)
        - If LP is integer: update incumbent
        - If LP is fractional: branch using configured branching rule
        - Prune by bound

    Args:
        dist_matrix (np.ndarray): Distance matrix (n_nodes+1 x n_nodes+1).
        wastes (Dict[int, float]): Waste volumes for each node.
        capacity (float): Vehicle capacity.
        R (float): Revenue per kg.
        C (float): Cost per km.
        params (Optional[Union[BPCParams, Dict[str, Any]]]): Configuration parameters.
        mandatory_indices (Optional[Set[int]]): Set of node indices that must be visited.
        vehicle_limit (Optional[int]): Fleet size limit.
        env (Optional[Any]): Gurobi environment (ignored, kept for compatibility).
        node_coords (Optional[np.ndarray]): Optional node coordinates for visualization.
        recorder (Optional[PolicyStateRecorder]): Optional state recorder for tracking.
        kwargs: Additional keyword arguments.

    Returns:
        Tuple[List[List[int]], float]: (Best routes found, best objective value).

    Example:
        >>> from logic.src.policies.route_construction.exact_and_decomposition_solvers.branch_and_price_and_cut.bpc_engine import run_bpc
        >>> dist_matrix = np.array([[0, 10], [10, 0]])
        >>> wastes = {1: 5.0}
        >>> routes, cost = run_bpc(dist_matrix, wastes, capacity=10, R=1, C=1)
    """
    start_time = time.perf_counter()
    n_nodes = len(dist_matrix) - 1
    m_set = mandatory_indices if mandatory_indices is not None else set()

    # Standardize params to BPCParams
    if params is None:
        params = BPCParams()
    elif isinstance(params, dict):
        params = BPCParams.from_config(params)

    # Configuration
    # Extract parameters from BPCParams
    max_cg_iter = params.max_cg_iterations
    max_cuts = params.max_cuts_per_iteration
    max_routes_per_pricing = params.max_routes_per_pricing
    max_bb_nodes = params.max_bb_nodes
    time_limit = params.time_limit
    search_strategy_name = params.search_strategy
    cutting_planes_name = params.cutting_planes
    branching_strategy_name = params.branching_strategy

    # Numerical Safety Warning
    if params.rc_tolerance > params.optimality_gap:
        warnings.warn(
            f"Optimality Risk: rc_tolerance ({params.rc_tolerance}) is coarser than "
            f"optimality_gap ({params.optimality_gap}). BPC may terminate prematurely "
            f"with a sub-optimal solution.",
            stacklevel=2,
        )

    # 1. Initialize Master Problem over the FULL instance.
    # No node pre-selection — BPC prices over all n_nodes simultaneously.
    # The RCSPP subproblem handles both node selection and routing via reduced costs.
    k_nodes = n_nodes
    red_dist = dist_matrix
    red_wastes = wastes
    red_mandatory = m_set

    master = VRPPMasterProblem(
        n_nodes=k_nodes,
        mandatory_nodes=red_mandatory,
        cost_matrix=red_dist,
        wastes=red_wastes,
        capacity=capacity,
        revenue_per_kg=R,
        cost_per_km=C,
        vehicle_limit=vehicle_limit,
    )

    # Task 3/6: Harden Ryan-Foster Exactness
    if branching_strategy_name == "ryan_foster":
        master.strict_set_partitioning = True
        logger.info("Enforcing strict Set Partitioning (SP) for Ryan-Foster branching.")

    # 2. Initial Columns — mandatory-only greedy warm-start on reduced instance
    mandatory_list = sorted(list(red_mandatory))
    if params.profit_aware_operators:
        initial_routes_nodes = greedy_profit_insertion(
            [],
            mandatory_list,
            red_dist,
            red_wastes,
            capacity,
            R=R,
            C=C,
            mandatory_nodes=mandatory_list,
            expand_pool=False,
        )
    else:
        initial_routes_nodes = greedy_insertion(
            [],
            mandatory_list,
            red_dist,
            red_wastes,
            capacity,
            mandatory_nodes=mandatory_list,
            expand_pool=False,
        )

    initial_columns = []
    pricing_solver = RCSPPSolver(
        k_nodes,
        red_dist,
        red_wastes,
        capacity,
        R,
        C,
        use_ng_routes=params.use_ng_routes,
        ng_neighborhood_size=min(params.ng_neighborhood_size, k_nodes - 1),
        node_prizes=kwargs.get("node_prizes"),
        timeout=params.rcspp_timeout,
        max_labels=params.rcspp_max_labels,
    )

    for r_nodes in initial_routes_nodes:
        route_obj = pricing_solver._compute_route_details(r_nodes)
        initial_columns.append(route_obj)

    # Seed with greedy optional-node routes so LP duals for optional nodes
    # are non-zero from the start, guiding the RCSPP toward optional nodes.
    all_local_nodes = list(range(1, k_nodes + 1))
    optional_local = [n for n in all_local_nodes if n not in red_mandatory]
    if optional_local and params.profit_aware_operators:
        try:
            opt_seed_routes = greedy_profit_insertion(
                [r for r in initial_routes_nodes],  # start from mandatory routes
                optional_local,
                red_dist,
                red_wastes,
                capacity,
                R=R,
                C=C,
                mandatory_nodes=mandatory_list,
                expand_pool=True,
            )
            for r_nodes in opt_seed_routes:
                if tuple(r_nodes) not in {tuple(r) for r in initial_routes_nodes}:
                    route_obj = pricing_solver._compute_route_details(r_nodes)
                    if route_obj.profit > 0:
                        initial_columns.append(route_obj)
            logger.info(
                f"[Warm-start] Added {len(opt_seed_routes) - len(initial_routes_nodes)} "
                f"optional-node seed routes to initial column pool."
            )
        except Exception as _e:
            logger.debug(f"[Warm-start] Optional seeding failed: {_e}")

    master.build_model(initial_columns)
    master.column_deletion_enabled = True

    # 2.1 Initialize 2-Phase Method
    # Start in Phase 1 (Feasibility) if there are mandatory nodes to cover.
    if len(red_mandatory) > 0:
        master.set_phase(1)
    else:
        master.set_phase(2)

    # 3. Initialize pricing and separation — use REDUCED instance throughout
    # pricing_solver is already initialized above on red_dist/red_wastes — reuse it.
    n_total_nodes = k_nodes + 1  # VRPPModel counts total nodes including depot (index 0)
    v_model = VRPPModel(
        n_nodes=n_total_nodes,
        cost_matrix=red_dist,
        wastes=red_wastes,
        capacity=capacity,
        revenue_per_kg=R,
        cost_per_km=C,
        mandatory_nodes=red_mandatory,
    )
    sep_engine = SeparationEngine(
        model=v_model,
        enable_heuristic_rcc_separation=params.enable_heuristic_rcc_separation,
        enable_comb_cuts=params.enable_comb_cuts,
    )

    # 4. Initialize Branch-and-Bound Tree with search strategy
    bb_tree = BranchAndBoundTree(
        v_model=v_model, params=params, search_strategy=search_strategy_name, strategy=branching_strategy_name
    )

    # 5. Initialize cutting engine
    cut_engine = create_cutting_plane_engine(
        cutting_planes_name,
        v_model,
        sep_engine,
        dist_matrix=red_dist,
        route_budget=getattr(params, "route_budget", float("inf")),
    )

    # ── Tier 1 + selection-routing duality supplemental cut engines ──────
    # These are always active regardless of cutting_planes_name, since they
    # specifically address the VRPP profit-selection × routing duality.
    from logic.src.policies.route_construction.exact_and_decomposition_solvers.branch_and_price_and_cut.cutting_planes import (
        CompositeCuttingPlaneEngine,
        LimitedMemoryRank1CutEngine,
        MinCutInequalityEngine,
        NodeProfitBoundEngine,
        PathEliminationEngine,
        TriangleCliqueCutEngine,
    )

    _supplemental_engines = [
        MinCutInequalityEngine(v_model),
        TriangleCliqueCutEngine(
            v_model, dist_matrix=red_dist, route_budget=getattr(params, "route_budget", float("inf"))
        ),
        LimitedMemoryRank1CutEngine(v_model, max_subset_size=5),
        NodeProfitBoundEngine(v_model),
        PathEliminationEngine(
            v_model, dist_matrix=red_dist, route_budget=getattr(params, "route_budget", float("inf"))
        ),
    ]
    # Wrap primary + supplemental engines together unless already "all"
    if cutting_planes_name not in ("all", "composite"):
        cut_engine = CompositeCuttingPlaneEngine([cut_engine] + _supplemental_engines)
    # If already "all", supplemental engines are already included
    nodes_explored = 0
    logger.info(f"BPC Solver started: full instance, {k_nodes} nodes, max BB nodes: {max_bb_nodes}")

    # 6. Branch-and-Bound Loop
    while not bb_tree.is_empty() and nodes_explored < max_bb_nodes:
        if time_limit > 0 and (time.perf_counter() - start_time) > time_limit:
            break

        # The BBTree now internally manages the frontier priority queues (tuples vs lists).
        # We natively extract the correct node using the tree's integrated logic.
        current_node = bb_tree.get_next_node()
        if current_node is None:
            break

        nodes_explored += 1
        bb_tree.record_explored()  # Keep tree-level counter accurate

        # Remove node-local cuts from the previous node before solving this one.
        master.remove_local_cuts()

        # Get ALL branching constraints along the path from root to this node
        # (ancestors + this node). _apply_branching_to_master resets all UBs
        # to 1.0 and re-filters against the full constraint set, so it requires
        # the complete ancestor chain — not just this node's local constraint.
        branching_constraints = current_node.get_all_constraints()

        # 3. Apply branching constraints to master and pricing
        _apply_branching_to_master(master, branching_constraints, branching_strategy_name)
        if master.model:
            master.model.update()

        # Run Column Generation at this node with corrected sequencing
        # ---------------------------------------------------------------
        # Lagrangian Pre-Pruning (optional, params.lr_pre_pruning)
        # ---------------------------------------------------------------
        # Run a fast subgradient pass before expensive column generation.
        # If the Lagrangian bound is dominated by the current incumbent,
        # the node is pruned without ever calling _column_generation_loop.
        # ---------------------------------------------------------------
        if (
            params.lr_pre_pruning
            and bb_tree.best_integer_solution is not None
            and (params.lr_pre_pruning_depth_limit < 0 or current_node.depth <= params.lr_pre_pruning_depth_limit)
        ):
            # Build forced sets from branching constraints accumulated at this node.
            _lr_forced_in, _lr_forced_out = _extract_forced_sets_from_constraints(current_node.constraints)
            # Union with global mandatory for the forced_in set.
            _lr_forced_in |= m_set

            # Time budget: a small fraction of remaining solve time, capped hard.
            _remaining = time_limit - (time.perf_counter() - start_time) if time_limit > 0 else 300.0
            _lr_budget = min(
                _remaining * 0.05,  # at most 5% of remaining wall time
                params.lr_op_time_limit * params.lr_max_subgradient_iters,
            )

            if _lr_budget > 0.5:  # skip if < 0.5 s available
                _lr_ub, _lam_star, _lr_op_visited = _compute_lr_bound_at_node(
                    dist_matrix=red_dist,
                    wastes=red_wastes,
                    capacity=capacity,
                    R=R,
                    C=C,
                    mandatory=_lr_forced_in,
                    forced_out=_lr_forced_out,
                    params=params,
                    time_budget=_lr_budget,
                    env=env,
                    recorder=recorder,
                )

                _gap_threshold = bb_tree.best_integer_solution * (1.0 + params.optimality_gap)

                if _lr_ub <= _gap_threshold:
                    # LR bound is dominated — prune without CG.
                    logger.debug(
                        f"[LR Pre-Pruning] Node depth={current_node.depth} pruned. "
                        f"LR bound={_lr_ub:.4f} <= incumbent={bb_tree.best_integer_solution:.4f}."
                    )
                    if recorder:
                        recorder.record(
                            engine="bpc_lr_pre_pruning",
                            node_depth=current_node.depth,
                            lr_upper_bound=_lr_ub,
                            lam_star=_lam_star,
                            incumbent=bb_tree.best_integer_solution,
                            pruned=True,
                        )
                    bb_tree.prune_by_bound()
                    continue

                if recorder:
                    recorder.record(
                        engine="bpc_lr_pre_pruning",
                        node_depth=current_node.depth,
                        lr_upper_bound=_lr_ub,
                        lam_star=_lam_star,
                        incumbent=bb_tree.best_integer_solution,
                        pruned=False,
                    )

                # LR did not prune. Optionally seed a warm-start column into the pool.
                if params.lr_warm_start_cg and _lr_op_visited:
                    _seed_nodes = sorted(_lr_op_visited - _lr_forced_out)
                    if _seed_nodes:
                        try:
                            _seed_route = pricing_solver._compute_route_details(_seed_nodes)
                            _seed_rc = master.calculate_reduced_cost(
                                _seed_route,
                                master.get_reduced_cost_coefficients(),
                            )
                            if _seed_rc > params.rc_tolerance:
                                master.add_route(_seed_route)
                                logger.debug(
                                    f"[LR Warm-Start] Seeded column from UOP at λ*={_lam_star:.4f}, "
                                    f"rc={_seed_rc:.4f}, nodes={_seed_nodes}."
                                )
                        except Exception as _e:
                            logger.debug(f"[LR Warm-Start] Column seeding failed: {_e}. Continuing.")
        # ---------------------------------------------------------------
        # End of LR Pre-Pruning block
        # ---------------------------------------------------------------

        try:
            # Snapshot-and-restore ng-neighborhoods
            ng_snapshot = pricing_solver.save_ng_snapshot()
            try:
                _node_start = time.perf_counter()
                _elapsed_global = _node_start - start_time
                _remaining_global = max(0.1, time_limit - _elapsed_global) if time_limit > 0 else 0.0
                if _remaining_global > 0.0 and current_node.depth == 0:
                    _node_budget = min(_remaining_global, time_limit * 0.40)
                else:
                    _node_budget = _remaining_global

                # Reduced-cost arc fixing: eliminate pricing arcs whose minimum
                # reduced cost exceeds the LP-incumbent gap (Irnich et al. 2010).
                # Use the parent node's LP bound as the current upper bound;
                # lp_obj for this node has not been computed yet.
                _parent_lp = (
                    current_node.parent.lp_bound
                    if current_node.parent is not None and current_node.parent.lp_bound is not None
                    else current_node.lp_bound
                )
                if (
                    bb_tree.best_integer_solution is not None
                    and _parent_lp is not None
                    and hasattr(pricing_solver, "_forbidden_arcs")
                ):
                    _n_fixed = _reduced_cost_arc_fixing(
                        pricing_solver=pricing_solver,
                        master_lp_bound=_parent_lp,
                        incumbent_value=bb_tree.best_integer_solution,
                        n_nodes=k_nodes,
                        dist_matrix=red_dist,
                        wastes=red_wastes,
                        node_duals=master.get_dual_values() if hasattr(master, "get_dual_values") else {},
                        capacity=capacity,
                        R=R,
                        C=C,
                    )
                    if _n_fixed > 0:
                        logger.debug(f"Reduced-cost arc fixing: eliminated {_n_fixed} arcs.")

                lp_obj, route_values, node_final_basis, node_timed_out = _column_generation_loop(
                    master=master,
                    pricing_solver=pricing_solver,
                    cut_engine=cut_engine,
                    branching_constraints=branching_constraints,
                    max_cg_iterations=max_cg_iter,
                    max_cuts=max_cuts,
                    time_limit=_node_budget,
                    start_time=_node_start,
                    max_routes_per_pricing=max_routes_per_pricing,
                    vehicle_limit=master.vehicle_limit,
                    optimality_gap=params.optimality_gap,
                    early_termination_gap=params.early_termination_gap,
                    parent_basis=current_node.parent.lp_basis if current_node.parent else None,
                    incumbent_value=bb_tree.best_integer_solution
                    if bb_tree.best_integer_solution is not None
                    else -float("inf"),
                    node_depth=current_node.depth,
                    rc_tolerance=params.rc_tolerance,
                    cut_orthogonality_threshold=params.cut_orthogonality_threshold,
                    exact_mode=params.exact_mode,
                    cg_at_root_only=params.cg_at_root_only,
                    branching_strategy=branching_strategy_name,
                    rcspp_timeout=params.rcspp_timeout,
                )
            finally:
                # Restore ng-neighborhoods so sibling nodes are unaffected by this
                # node's dynamic ng-expansion.
                pricing_solver.restore_ng_snapshot(ng_snapshot)

            # Task 3: Global Time Limit tracking
            if node_timed_out:
                logger.warning(f"B&B node at depth {current_node.depth} timed out. Terminating search.")
                break
            current_node.lp_basis = node_final_basis
        except BPCPruningException:
            # Node provably cannot improve the incumbent — skip without marking infeasible
            continue
        except gp.GurobiError as e:
            # GurobiError (e.g. licensing, memory, degenerate model) is not a RuntimeError,
            # so it would escape the inner except and propagate to checkpoint_manager,
            # converting to CheckpointError and silently terminating the simulation.
            logger.warning(
                "GurobiError at B&B node depth=%d: %s. Marking node infeasible.",
                current_node.depth,
                e,
            )
            current_node.is_infeasible = True
            continue
        except RuntimeError as e:
            if "Conflicting must_use" in str(e):
                current_node.is_infeasible = True
                continue
            # LP infeasible at this node (regular RuntimeError)
            current_node.is_infeasible = True
            continue

        # Store LP bound
        current_node.lp_bound = lp_obj
        current_node.route_values = route_values

        # Global optimality gap check
        if bb_tree.best_integer_solution is not None:
            # Safely retrieve the best bound via the tree's statistics method,
            # which internally handles tuple unpacking and priority inversions.
            stats = bb_tree.get_statistics()
            best_open_lp_bound = stats.get("best_bound")
            if best_open_lp_bound is None:
                best_open_lp_bound = lp_obj

            # Always include the current node's LP value in the upper bound.
            global_upper_bound = max(best_open_lp_bound, lp_obj)
            # Use a stable denominator: at least 1.0, anchored to problem scale.
            denom = max(
                abs(bb_tree.best_integer_solution),
                abs(global_upper_bound),
                1.0,
            )
            global_gap = (global_upper_bound - bb_tree.best_integer_solution) / denom

            if global_gap <= params.optimality_gap:
                logger.info(f"Global optimality gap reached: {global_gap:.6f} <= {params.optimality_gap}")
                break

            # Reduced Cost Edge Fixing (Globally valid at every node)
            # We use the global_upper_bound (max of all open node bounds and current)
            # to ensure arc fixing is mathematically sound for all sibling branches.
            _apply_reduced_cost_edge_fixing(
                master=master,
                pricing_solver=pricing_solver,
                z_ub=global_upper_bound,
                z_lb=bb_tree.best_integer_solution,
            )

        # Check if solution is integer FIRST — before pruning
        if _is_solution_integer(master.routes, route_values):
            current_node.is_integer = True
            current_node.ip_solution = lp_obj

            # Update incumbent (records equal or better solutions)
            bb_tree.update_incumbent(current_node, lp_obj)
            bb_tree.prune_by_bound()

            # After recording, prune this node (no need to branch)
            continue

        # Check if we can prune by bound (strictly less than incumbent, since integer
        # solutions equal to incumbent were already handled above)
        if bb_tree.best_integer_solution is not None and lp_obj <= bb_tree.best_integer_solution:
            bb_tree.prune_by_bound()  # Ensure stale nodes are removed
            continue

        # Solution is fractional - branch
        if getattr(params, "enable_column_pool_deduplication", False):
            purged = master.deduplicate_column_pool()
            if purged > 0:
                logger.info(f"Deduplicated {purged} equivalent routes from column pool.")

        strong_candidate = None
        if getattr(params, "enable_strong_branching_heuristic", False):
            candidates = bb_tree.find_strong_branching_candidates(master.routes, route_values, max_candidates=5)
            if candidates:
                strong_candidate = _perform_strong_branching(
                    master=master,
                    candidates=candidates,
                    current_node=current_node,
                    strong_branching_size=getattr(params, "strong_branching_size", 5),
                )

        # ── Hierarchical node-visitation branching (Boussier et al. 2007) ────
        # Branch on y_v BEFORE arc/Ryan-Foster decisions to directly resolve
        # the profit-selection × routing duality.
        _y_branch_result = None
        optional_nodes = {i for i in range(1, k_nodes + 1) if i not in red_mandatory}
        if optional_nodes and getattr(params, "enable_node_visitation_branching", True):
            from logic.src.policies.helpers.solvers_and_matheuristics.branching.strategies import (
                HierarchicalStrongBranching,
            )

            _y_branch_result = HierarchicalStrongBranching.find_best_y_branching(
                routes=master.routes,
                route_values=route_values,
                optional_nodes=optional_nodes,
                master=master if getattr(params, "enable_strong_branching_heuristic", False) else None,
                phase1_size=getattr(params, "strong_branching_size", 5),
                phase2_size=max(2, getattr(params, "strong_branching_size", 5) // 2),
            )
            if _y_branch_result is not None:
                _y_node, _y_val = _y_branch_result
                left_child, right_child = HierarchicalStrongBranching.create_child_nodes(current_node, _y_node, _y_val)
                children = (left_child, right_child)
                logger.debug(f"Node-visitation branch on y_{_y_node}={_y_val:.3f} at depth {current_node.depth}.")
                # Skip the standard arc/RF branching when y-branching was applied
                left_child.lp_bound = lp_obj
                right_child.lp_bound = lp_obj
                bb_tree.add_node(left_child)
                bb_tree.add_node(right_child)
                continue  # proceed to next B&B node

        children = bb_tree.branch(
            current_node,
            master.routes,
            route_values,
            mandatory_nodes=master.mandatory_nodes,
            strong_candidate=strong_candidate,
        )

        if children is not None:
            left_child, right_child = children
            # If Ryan-Foster was selected at any level, we must harden the master to
            # strict Set Partitioning. Failure to do so allows over-covering solutions
            # to satisfy the "together" branch constraint, invalidating the bound.
            rf_used = getattr(left_child, "branching_rule", None) == "ryan_foster"
            if rf_used and not master.strict_set_partitioning:
                logger.warning(
                    "Ryan-Foster branching activated at a non-RF-primary node. "
                    "Hardening master to strict Set Partitioning for correctness."
                )
                master.strict_set_partitioning = True

        if children is None:
            # Primary branching strategy found no candidate (e.g., divergence branching
            # requires >=2 outgoing arcs at a divergence node but none exist).
            # Fall back to edge branching to avoid silently abandoning this fractional node.
            logger.warning(
                f"Primary branching strategy '{branching_strategy_name}' returned no "
                "branching candidate at a fractional node. Falling back to edge branching."
            )
            from logic.src.policies.helpers.solvers_and_matheuristics.branching import EdgeBranching

            res = EdgeBranching.find_branching_arc(master.routes, route_values)
            if res is None:
                # Truly no branching candidate — node is degenerate, skip it.
                logger.warning("Edge branching fallback also found no candidate. Skipping node.")
                continue
            (u, v), flow = res
            left_child, right_child = EdgeBranching.create_child_nodes(current_node, u, v, flow)
            children = (left_child, right_child)

        left_child, right_child = children
        use_paper_ordering = (
            getattr(params, "prefer_shorter_path_dfs", True)
            and branching_strategy_name == "divergence"
            and bb_tree.search_strategy not in ("best_first", "best-first")
        )

        if use_paper_ordering:
            # Paper §3.2: right_child (shorter path kept) explored first.
            # Push left_child first (popped last), right_child last (popped first).
            bb_tree.add_node(left_child)  # pushed first → popped last (explored second)
            bb_tree.add_node(right_child)  # pushed last  → popped first (paper §3.2)
        else:
            # LP-hint-guided ordering (non-divergence branching, or best_first mode,
            # or prefer_shorter_path_dfs=False). Explore the child with the stronger
            # LP bound first; when equal, use the child with fewer local constraints.
            hint_l = left_child.lp_bound if left_child.lp_bound is not None else -float("inf")
            hint_r = right_child.lp_bound if right_child.lp_bound is not None else -float("inf")

            if hint_l < hint_r:
                # Right child is stronger (higher bound) — push left first, right last
                bb_tree.add_node(left_child)
                bb_tree.add_node(right_child)
            elif hint_r < hint_l:
                # Left child is stronger — push right first, left last
                bb_tree.add_node(right_child)
                bb_tree.add_node(left_child)
            else:
                # Tie-break: explore child with fewer local constraints first
                # (LP closer to parent basis → better warm-start).
                if len(left_child.constraints) <= len(right_child.constraints):
                    bb_tree.add_node(right_child)  # pushed first = popped last
                    bb_tree.add_node(left_child)  # pushed last  = popped first
                else:
                    bb_tree.add_node(left_child)
                    bb_tree.add_node(right_child)

    # 6. Extract best integer solution
    if bb_tree.best_integer_node is None:
        # No integer solution found — return mandatory-only greedy routes
        fallback_profit = 0.0
        for r_nodes in initial_routes_nodes:
            fallback_profit += pricing_solver._compute_route_details(r_nodes).profit
        return initial_routes_nodes, fallback_profit

    # Reconstruct solution from best node
    best_node = bb_tree.best_integer_node
    best_routes_objects = [
        master.routes[idx]
        for idx, val in best_node.route_values.items()  # type: ignore[union-attr]
        if val > 0.5
    ]

    final_routes = [r.nodes for r in best_routes_objects]
    final_cost = sum(r.profit for r in best_routes_objects)

    if recorder:
        recorder.record(
            engine="exact_bpc",
            iterations=nodes_explored,
            obj_val=bb_tree.best_integer_solution,
            n_routes=len(final_routes),
        )

    return final_routes, final_cost
