import copy
import random
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from logic.src.enums import GlobalRegistry, PolicyTag
from logic.src.interfaces.context.multi_day_context import MultiDayContext
from logic.src.interfaces.context.problem_context import ProblemContext
from logic.src.interfaces.context.solution_context import SolutionContext
from logic.src.policies.route_construction.base.base_multi_period_policy import BaseMultiPeriodRoutingPolicy
from logic.src.policies.route_construction.base.factory import RouteConstructorRegistry
from logic.src.policies.route_construction.hyper_heuristics.genetic_programming_multi_period_hyper_heuristic.params import (
    GP_MP_HH_Params,
)
from logic.src.utils.helpers.llh_pool import LLHPool
from logic.src.utils.helpers.routes import route_profit
from logic.src.utils.helpers.wrappers import greedy_day_route


@GlobalRegistry.register(
    PolicyTag.HYPER_HEURISTIC,
    PolicyTag.EVOLUTIONARY_ALGORITHM,
    PolicyTag.MULTI_PERIOD,
    PolicyTag.CONSTRUCTION,
    PolicyTag.PROFIT_AWARE,
)
@RouteConstructorRegistry.register("gp_mp_hh")
class GPMPHHPolicy(BaseMultiPeriodRoutingPolicy):
    """
    Genetic Programming Multi-Period Hyper-Heuristic (GP-MP-HH).

    GP-MP-HH evolves a "program" or sequence of Low-Level Heuristics (LLHs) that
    are applied sequentially to an initial solution. By evolving the program
    structure, the hyper-heuristic discovers complex operator combinations
    specifically tailored to the problem instance and rolling horizon state.

    Search Logic:
    1. **Program Representation**: Each individual in the population is an
       ordered sequence of LLH indices.
    2. **Execution**: A base greedy plan is transformed by applying each
       heuristic in the program's sequence.
    3. **Evolution**: Uses tournament selection, single-point crossover, and
       point mutation to improve the population of programs over multiple
       generations.
    4. **Fitness**: Evaluated by the total expected profit of the resulting
       multi-period collection plan.

    Registry key: ``"gp_mp_hh"``
    """

    def __init__(self, config: Any = None):
        super().__init__(config)
        self.params = GP_MP_HH_Params.from_config(config)
        self.pop_size = self.params.pop_size
        self.gens = self.params.gens
        self.prog_len = self.params.prog_len
        self.seed = self.params.seed
        self.rng = random.Random(self.seed)
        self.llhs = LLHPool.get_all()

    def _evaluate(self, plan: List[List[List[int]]], problem: ProblemContext) -> float:
        tot = 0.0
        cur_prob = problem
        for d in range(problem.horizon):
            rt = plan[d][0] if plan[d] else []
            tot += route_profit(rt, cur_prob)
            cur_prob = cur_prob.advance(rt)
        return tot

    def _run_multi_period_solver(
        self,
        problem: ProblemContext,
        multi_day_ctx: Optional[MultiDayContext],
    ) -> Tuple[SolutionContext, List[List[List[int]]], Dict[str, Any]]:
        """
        Execute the Genetic Programming Hyper-Heuristic solver.

        Args:
            problem: The current ProblemContext containing state data.
            multi_day_ctx: Optional context for spanning multiple rolling days.

        Returns:
            Tuple[SolutionContext, List[List[List[int]]], Dict[str, Any]]:
                - today_solution: Standardized solution context for Day 0.
                - best_plan: Multi-period plan generated by the best program.
                - stats: Execution statistics (generations, best fitness).
        """
        np_rng = np.random.default_rng(self.seed)

        # Initial base plan
        cur_plan = []
        cur_prob = problem
        for _d in range(problem.horizon):
            rt = greedy_day_route(cur_prob, np_rng)
            cur_plan.append([rt])
            cur_prob = cur_prob.advance(rt)

        # Population of sequences of LLH indices
        pop = [[self.rng.randint(0, len(self.llhs) - 1) for _ in range(self.prog_len)] for _ in range(self.pop_size)]

        # Initialize with a valid empty structure to satisfy Mypy
        best_plan: List[List[List[int]]] = [[] for _ in range(problem.horizon)]
        best_prof = -float("inf")

        for _ in range(self.gens):
            fitnesses = []
            plans = []

            for j in range(self.pop_size):
                prog = pop[j]
                p = copy.deepcopy(cur_plan)

                # Execute program
                for idx in prog:
                    cmd = self.llhs[idx]
                    p = cmd(p, problem, self.rng)

                prof = self._evaluate(p, problem)
                fitnesses.append(prof)
                plans.append(p)

                if prof > best_prof:
                    best_prof = prof
                    best_plan = copy.deepcopy(p)

            # Selection and crossover (simple tournament + 1pt Xover)
            new_pop = []
            for _ in range(self.pop_size):
                t1, t2 = self.rng.sample(range(self.pop_size), 2)
                p1 = pop[t1] if fitnesses[t1] > fitnesses[t2] else pop[t2]

                t1, t2 = self.rng.sample(range(self.pop_size), 2)
                p2 = pop[t1] if fitnesses[t1] > fitnesses[t2] else pop[t2]

                xpt = self.rng.randint(1, self.prog_len - 1)
                child = p1[:xpt] + p2[xpt:]

                # Mutate
                if self.rng.random() < 0.1:
                    mpt = self.rng.randint(0, self.prog_len - 1)
                    child[mpt] = self.rng.randint(0, len(self.llhs) - 1)

                new_pop.append(child)

            pop = new_pop

        today_route = best_plan[0][0] if best_plan[0] else []
        sol = SolutionContext.from_problem(problem, today_route)

        return sol, best_plan, {"gphh_gens": self.gens, "expected_profit": best_prof}
