# @package _global_
kgls:
  time_limit: 60.0
  local_search_iterations: 100
  num_perturbations: 3
  neighborhood_size: 20
  moves:
    - relocate
    - swap
    - two_opt
    - cross_exchange
  penalization_cycle:
    - width
    - length
    - width_length
  mandatory_selection: ["other/ms_lookahead.yaml"]

  # VRPP Settings
  vrpp: true
  profit_aware_operators: false

  route_improvement: []
