"""State-space search tree node for Branch-and-Bound.

Each node in the tree represents a subproblem where a subset of binary decision
variables (edges and node visits) has been fixed to specific integer values.

Attributes:
    Node: Simple data structure for B&B nodes.
    BranchNode: Advanced node structure for Branch-and-Price-and-Cut.

Example:
    >>> node = BranchNode(depth=1, lp_bound_hint=100.0)
    >>> constraints = node.get_all_constraints()
"""

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple

if TYPE_CHECKING:
    from logic.src.policies.helpers.solvers_and_matheuristics.branching.constraints import AnyBranchingConstraint
    from logic.src.policies.helpers.solvers_and_matheuristics.common.route import Route


@dataclass(order=True)
class Node:
    """Represents a discrete node in the Branch-and-Bound exploration tree.

    Nodes are prioritized in the search queue based on their lower bound (LB)
    Attributes:
        bound (float): LP relaxation value (upper bound for maximization).
        fixed_x (Dict[Tuple[int, int], int]): Mapping of edges to their fixed binary values.
        fixed_y (Dict[int, int]): Mapping of nodes to their fixed visitation values.
        depth (int): The distance of the node from the root of the search tree.


    Example:
        >>> node = Node(bound=100.0, depth=0)
    """

    bound: float = field(compare=True)  # LP relaxation value (upper bound for maximization)
    fixed_x: Dict[Tuple[int, int], int] = field(compare=False, default_factory=dict)
    fixed_y: Dict[int, int] = field(compare=False, default_factory=dict)
    depth: int = field(compare=False, default=0)


class BranchNode:
    """
    A single node in the Branch-and-Price-and-Cut search tree.

    Attributes:
        constraints (List[AnyBranchingConstraint]): Constraints added at this node only.
        parent (Optional[BranchNode]): Parent node in the tree.
        depth (int): Current tree depth.
        branching_rule (str): Name of the rule used to create this node.
        lp_bound (Optional[float]): LP relaxation bound at this node.
        ip_solution (Optional[float]): Best integer solution found in this subtree.
        is_integer (bool): True if the LP solution is integer.
        is_infeasible (bool): True if the subproblem is infeasible.
        is_explored (bool): True if the node has been processed.
        is_pruned (bool): True if the node was pruned.
        route_values (Optional[Dict[int, float]]): LP solution λ_k values.
        routes (Optional[List[Route]]): Local subset of columns maintained at this node.
        lp_basis (Optional[Any]): Gurobi basis for warm-starting.
        children (List[BranchNode]): Child nodes generated by branching.


    Example:
        >>> parent = BranchNode(depth=0)
        >>> child = BranchNode(parent=parent, depth=1)
    """

    def __init__(
        self,
        constraints: Optional[List["AnyBranchingConstraint"]] = None,
        parent: Optional["BranchNode"] = None,
        depth: int = 0,
        lp_bound_hint: Optional[float] = None,
        branching_rule: str = "none",
    ) -> None:
        """
        Initialise a branch node.

        Args:
            constraints: Constraints added *at this node only* (not inherited).
            parent: Parent node (None for root).
            depth: Tree depth (root = 0).
            lp_bound_hint: Optional initial LP bound (inherited from parent).
            branching_rule: Name of the rule used to create this node's branch.
        """
        self.constraints: List["AnyBranchingConstraint"] = constraints or []
        self.parent: Optional["BranchNode"] = parent
        self.depth: int = depth
        self.branching_rule = branching_rule

        # State tracking
        self.lp_bound: Optional[float] = lp_bound_hint
        self.ip_solution: Optional[float] = None
        self.is_integer: bool = False
        self.is_infeasible: bool = False
        self.is_explored: bool = False
        self.is_pruned: bool = False

        # Solution data
        self.route_values: Optional[Dict[int, float]] = None
        self.routes: Optional[List["Route"]] = None
        self.lp_basis: Optional[Any] = None

        self.children: List["BranchNode"] = []

    def get_all_constraints(self) -> List["AnyBranchingConstraint"]:
        """
        Return all active constraints from the root down to this node.

        Returns:
            Flat list in root-to-leaf order.
        """
        constraints: List["AnyBranchingConstraint"] = []
        node: Optional["BranchNode"] = self
        while node is not None:
            # Reverse node local constraints to keep consistent order if multiple exist
            constraints.extend(node.constraints[::-1])
            node = node.parent
        return constraints[::-1]

    def is_route_feasible(self, route: "Route") -> bool:
        """Return True if *route* satisfies every inherited constraint.

        Args:
            route: Route to validate.

        Returns:
            True if feasible, False otherwise.
        """
        return all(c.is_route_feasible(route) for c in self.get_all_constraints())

    def __lt__(self, other: "BranchNode") -> bool:
        """Priority for best-first search (higher bound is better for maximization).

        Args:
            other: Another BranchNode to compare against.

        Returns:
            bool: True if this node has a higher LP bound than the other.
        """

        b1 = self.lp_bound if self.lp_bound is not None else -1e10
        b2 = other.lp_bound if other.lp_bound is not None else -1e10
        return b1 > b2

    def __repr__(self) -> str:
        """Return a developer-friendly string representation.

        Returns:
            str: String representation of the BranchNode.
        """

        bound_str = f"{self.lp_bound:.2f}" if self.lp_bound is not None else "None"
        return f"BranchNode(depth={self.depth}, bound={bound_str}, constraints={len(self.constraints)})"
