"""
SRC (Sequential Route Constructor) — Meta-Constructor for Routing.
"""

from __future__ import annotations

import logging
import time
from typing import TYPE_CHECKING, Any, List, Optional, Tuple, Union

if TYPE_CHECKING:
    from logic.src.policies.context.multi_day_context import MultiDayContext
    from logic.src.policies.context.search_context import SearchContext

from logic.src.interfaces.route_constructor import IRouteConstructor
from logic.src.policies.context.search_context import SearchContext

from ...base.base_routing_policy import BaseRoutingPolicy
from ...base.registry import RouteConstructorRegistry
from .params import SRCParams

logger = logging.getLogger(__name__)


@RouteConstructorRegistry.register("src")
class SequentialRouteConstructor(BaseRoutingPolicy):
    """
    Sequential Route Constructor (SRC) - Pipeline Orchestrator for Routing.

    The SRC is a meta-policy that coordinates the execution of multiple
    underlying routing policies in a fixed sequence. This "pipeline" approach
    allows for complex, multi-stage optimization flows where each policy
    refines the solution generated by its predecessor.

    Example Workflow:
    1.  **NNPolicy**: Rapidly construct an initial feasible solution using a
        Nearest Neighbor heuristic.
    2.  **TSPolicy**: Refine the initial tour using Tabu Search to escape
        local optima.
    3.  **ALNSPolicy**: Apply Large Neighborhood Search to further optimize
        the routing arrangement.

    Each sub-constructor in the sequence receives the current tour, cost,
    profit, and contexts (search/multi-day) as input, allowing for continuous
    state propagation and incremental improvement.

    Registry key: ``"src"``
    """

    def __init__(self, config: Any = None):
        """
        Initialize the Sequential Route Constructor.

        Args:
            config: Either a SRCConfig dataclass or a dict.
        """
        super().__init__(config)
        self.constructors: List[IRouteConstructor] = []
        self._initialized = False

        # Load params
        if self.config is not None:
            self.params = SRCParams.from_config(self.config)
        else:
            self.params = SRCParams(constructors=["tsp", "nn"])

    @classmethod
    def _config_class(cls):
        from logic.src.configs.policies.src import SRCConfig

        return SRCConfig

    @classmethod
    def _get_config_key(cls) -> str:
        return "src"

    def _initialize_constructors(self) -> None:
        """Lazily initialize sub-constructors to avoid circular dependencies and registry issues."""
        if self._initialized:
            return

        from ...base.factory import RouteConstructorFactory

        # resolve names from params
        constructor_names = self.params.constructors

        self.constructors = [RouteConstructorFactory.get_adapter(name) for name in constructor_names]
        self._initialized = True

    def execute(
        self,
        **kwargs: Any,
    ) -> Tuple[
        Union[List[int], List[List[int]]],
        float,
        float,
        Optional[SearchContext],
        Optional[MultiDayContext],
    ]:
        """
        Execute a sequence of route constructors to progressively refine the solution.

        The Sequential Route Constructor (SRC) implements a pipeline-based routing
        strategy where multiple policies (e.g., NN followed by TS followed by
        2-Opt) are executed in order. Each policy takes the "current_tour" and
        "current_cost" from the previous stage as its starting point. This
        allows for complex hybrid strategies, such as using a neural model for
        initial construction followed by classical meta-heuristics for refinement.

        Args:
            **kwargs: Context dictionary containing:
                - tour (Optional[Union[List[int], List[List[int]]]]): Initial
                  tour to refine.
                - search_context (Optional[SearchContext]): Context for tracking
                  recursive solver statistics.
                - multi_day_context (Optional[MultiDayContext]): Context for
                  inter-day state propagation.

        Returns:
            Tuple[Union[List[int], List[List[int]]], float, float, Optional[SearchContext], Optional[MultiDayContext]]:
                A 5-tuple containing:
                - tour: The final refined collection routes.
                - cost: Total travel cost of the final routes.
                - profit: Total net profit calculated for the final routes.
                - search_context: The enriched search context after all phases.
                - multi_day_context: The final multi-day state metadata.
        """
        self._initialize_constructors()

        start_time = time.perf_counter()

        # Initialize with incoming state or valid default empty tour
        current_tour: Union[List[int], List[List[int]]] = kwargs.get("tour", [0, 0])
        current_cost: float = kwargs.get("cost", 0.0)
        current_profit: float = kwargs.get("profit", 0.0)
        current_context: Optional[SearchContext] = kwargs.get("search_context")
        current_multi_day: Optional[MultiDayContext] = kwargs.get("multi_day_context")

        for i, constructor in enumerate(self.constructors):
            # Check time limit
            elapsed = time.perf_counter() - start_time
            if elapsed > self.params.time_limit:
                logger.warning(
                    f"SRC time limit reached ({elapsed:.2f}s > {self.params.time_limit}s). "
                    f"Aborting sequence after {i} constructors."
                )
                break

            # Update kwargs to thread the state forward
            kwargs["tour"] = current_tour
            kwargs["cost"] = current_cost
            kwargs["profit"] = current_profit
            kwargs["search_context"] = current_context
            kwargs["multi_day_context"] = current_multi_day

            current_tour, current_cost, current_profit, current_context, current_multi_day = constructor.execute(
                **kwargs
            )

        return current_tour, current_cost, current_profit, current_context, current_multi_day

    def _run_solver(
        self,
        sub_dist_matrix: Any,
        sub_wastes: Any,
        capacity: float,
        revenue: float,
        cost_unit: float,
        values: Any,
        mandatory_nodes: List[int],
        **kwargs: Any,
    ) -> Tuple[List[List[int]], float, float]:
        """Not used as execute() is overridden directly."""
        return [], 0.0, 0.0
