"""Dynamic Hyper-Network connections.

This module provides the DynamicHyperConnection layer, which adaptively
generates transformation weights based on the input context to mix information
across multiple streams.

Attributes:
    DynamicHyperConnection: DYHCN layer for context-aware weight generation.

Example:
    >>> import torch
    >>> from torch import nn
    >>> from logic.src.models.subnets.modules.dynamic_hyper_connection import DynamicHyperConnection
    >>> module = nn.Linear(128, 128)
    >>> model = DynamicHyperConnection(module, embed_dim=128, n=4)
    >>> h = torch.randn(1, 10, 128, 4)
    >>> out = model(h)
"""

from __future__ import annotations

from typing import Any

import torch
from torch import nn


class DynamicHyperConnection(nn.Module):
    """Dynamic Hyper-Connection Network (DyHCN).

    Dynamically generates connection weights based on input context using a
    predictor network. This allows state-dependent mixing of information streams.

    Attributes:
        module (nn.Module): The transformation sub-module (e.g., Attention, MLP).
        n (int): Number of parallel information streams.
        embed_dim (int): Dimensionality of the input feature space.
        num_params (int): Count of parameters generated by the hyper-predictor.
        predictor (nn.Sequential): Hyper-network mapping context to mixing matrices.
    """

    def __init__(self, module: nn.Module, embed_dim: int, n: int = 4) -> None:
        """Initializes DynamicHyperConnection.

        Args:
            module: The internal layer to wrap (transformer sub-layer).
            embed_dim: Feature dimensionality of the nodes.
            n: Number of streams maintained by the hyper-connection.
        """
        super().__init__()
        self.module = module
        self.n = n
        self.embed_dim = embed_dim

        # Calculate total parameters needed for matrices: n*n (width) + n (input) + n (depth)
        self.num_params = (self.n * self.n) + self.n + self.n

        # Predictor Network: Maps input embedding -> Matrix Weights
        self.predictor = nn.Sequential(
            nn.Linear(embed_dim, embed_dim // 4),
            nn.ReLU(),
            nn.Linear(embed_dim // 4, self.num_params),
        )

        self._initialize_identity_bias()

    def _initialize_identity_bias(self) -> None:
        """Initializes predictor bias to favor identity transformations.

        Forces the hyper-network to output an identity matrix for width mixing
        and zero for cross-stream mixing at initialization to improve convergence.
        """
        # Set weights to near-zero so bias dominates at initialization
        nn.init.uniform_(self.predictor[-1].weight, -0.0001, 0.0001)

        n = self.n
        # Width Mixer (A_r) target: Flattened Identity Matrix
        target_width = torch.eye(n).flatten()
        # Input (A_m) and Depth (B) targets: Zeros (or small random)
        target_others = torch.zeros(2 * n)

        initial_bias = torch.cat([target_width, target_others])
        self.predictor[-1].bias.data.copy_(initial_bias)

    def forward(self, H: torch.Tensor, *args: Any, **kwargs: Any) -> torch.Tensor:
        """Applies context-dependent mixing to input streams.

        Args:
            H: Stream tensor of shape (batch, seq, dim, n).
            args: Positional arguments for the wrapped `module`.
            kwargs: Keyword arguments for the wrapped `module`.

        Returns:
            torch.Tensor: Mixed output streams of shape (batch, seq, dim, n).
        """
        # 1. Generate a proxy input for the predictor (e.g., mean of streams)
        x_proxy = H.mean(dim=-1)  # (B, S, D)

        # 2. Predict Weights for this specific input
        params = self.predictor(x_proxy)

        # Split params into A_r, A_m, B
        n = self.n
        B, S, _ = params.shape

        # Width (n*n), Input (n), Depth (n)
        P_width = params[..., : n * n].view(B, S, n, n)  # (B, S, n, n)
        P_input = params[..., n * n : n * n + n].view(B, S, n, 1)  # (B, S, n, 1)
        P_depth = params[..., n * n + n :].view(B, S, 1, n)  # (B, S, 1, n)

        # Input Mixer: sum_k (H_{ijk} * P_input_{ij k})
        h_in = torch.einsum("bsdn,bsnk->bsd", H, P_input)

        # 4. Apply Sub-layer
        y = self.module(h_in, *args, **kwargs)

        # 5. Update Hyper Matrix
        # Width: H x P_width
        term_width = torch.einsum("bsdn,bsnm->bsdm", H, P_width)

        # Depth: y x P_depth
        term_depth = torch.einsum("bsd,bsmn->bsdn", y, P_depth)

        return term_width + term_depth
