"""
Branch-and-Bound (BB) Policy Adapter.

Adapts the core mathematical Branch-and-Bound logic to the systems-agnostic
policy interface, handling parameter mapping, profit calculation, and environment
integration.
"""

from typing import Any, Dict, List, Optional, Tuple, Type, Union

import numpy as np

from logic.src.configs.policies import BBConfig
from logic.src.policies.route_construction.base.base_routing_policy import BaseRoutingPolicy
from logic.src.policies.route_construction.base.factory import RouteConstructorRegistry

from .dispatcher import run_bb_optimizer
from .params import BBParams


@RouteConstructorRegistry.register("bb")
class BranchAndBoundPolicy(BaseRoutingPolicy):
    """
    Adapter for the exact Branch-and-Bound routing solver.

    This policy implements a deterministic Best-Bound-First Branch-and-Bound
    search engine based on LP relaxations, mapping high-level simulation
    states (fill levels, distance matrices) into a structured mathematical
    programming model.

    The custom Python implementation of the B&B tree is purposefully designed
    for **full observability of the search state**, enabling the internal
    integration of machine learning components (e.g., neural branching
    heuristics) that are otherwise opaque in closed-source commercial solvers.

    As an exact solver, it guarantees global optimality within the specified
    MIP gap, provided the search terminates within the time limit.
    """

    def __init__(self, config: Optional[Union[BBConfig, Dict[str, Any]]] = None):
        """Initialize the BB policy adapter.

        Args:
            config: A typed BBConfig dataclass, a raw dictionary for parsing,
                or None to use framework defaults.
        """
        super().__init__(config)

    @classmethod
    def _config_class(cls) -> Optional[Type]:
        """Return the configuration dataclass type for automatic parsing."""
        return BBConfig

    def _get_config_key(self) -> str:
        """Return the unique identification key for this policy's configuration."""
        return "bb"

    def _run_solver(
        self,
        sub_dist_matrix: np.ndarray,
        sub_wastes: Dict[int, float],
        capacity: float,
        revenue: float,
        cost_unit: float,
        values: Dict[str, Any],
        mandatory_nodes: List[int],
        **kwargs: Any,
    ) -> Tuple[List[List[int]], float, float]:
        """
        Execute the exact Branch-and-Bound (B&B) solver logic.

        This method coordinates the search for a globally optimal routing solution
        by exploring a tree of linear relaxations. The search is pruned using
        incumbent integer solutions and lower bounds generated by either the
        MTZ (Miller-Tucker-Zemlin) compact formulation or the DFJ
        (Dantzig-Fulkerson-Johnson) formulation with lazy subset elimination
        constraints.

        In this implementation:
        -MTZ: Uses a compact polynomial number of constraints, suitable for
         customizing the search tree behavior.
        -DFJ: Leverages exponential constraints with dynamic sub-tour
         elimination, yielding tighter relaxations and faster convergence for
         standard problems.

        Args:
            sub_dist_matrix (np.ndarray): Symmetric distance matrix for the current
                sub-problem nodes.
            sub_wastes (Dict[int, float]): Mapping of local node indices to their
                current bin inventory levels.
            capacity (float): Maximum vehicle collection capacity.
            revenue (float): Revenue obtained per kilogram of waste collected.
            cost_unit (float): Monetary cost incurred per kilometer traveled.
            values (Dict[str, Any]): Merged configuration dictionary containing
                BB parameters (formulation, mip_gap, time_limit).
            mandatory_nodes (List[int]): Local indices of bins that MUST be
                collected in this period.
            **kwargs: Additional context, including:
                - search_context (Optional[SearchContext]): Context for tracking
                  recursive solver statistics.
                - multi_day_context (Optional[MultiDayContext]): Context for
                  inter-day state propagation.

        Returns:
            Tuple[List[List[int]], float, float]: A 3-tuple containing:
                - routes: Optimized collection routes (list-of-lists, local indices).
                - profit: Total calculated net profit (Total Revenue - Total Cost).
                - cost: Total travel cost calculated by the solver.
        """
        # Convert local mandatory indices to a set for fast lookup in branching
        mandatory_indices = set(mandatory_nodes)

        # Standardize configuration to BBParams
        params = BBParams.from_config(values)

        # Trigger core solver logic with formulation dispatch
        routes, solver_cost = run_bb_optimizer(
            dist_matrix=sub_dist_matrix,
            wastes=sub_wastes,
            capacity=capacity,
            R=revenue,
            C=cost_unit,
            params=params,
            mandatory_indices=mandatory_indices,
            env=kwargs.get("model_env"),
            recorder=kwargs.get("recorder"),
        )

        # Internal Profit Calculation: Revenue - Distance Cost
        # This mirrors the objective used during the search for consistency.
        visited = {n for route in routes for n in route}
        collected_revenue = sum(sub_wastes.get(n, 0) * revenue for n in visited)
        dist_cost = 0.0
        for route in routes:
            path = [0] + route + [0]
            for i in range(len(path) - 1):
                dist_cost += sub_dist_matrix[path[i]][path[i + 1]]
        profit = collected_revenue - dist_cost * cost_unit

        monetary_travel_cost = dist_cost * cost_unit
        return routes, profit, monetary_travel_cost
