"""
Global styling and effects.

This file acts as a facade for the gui.src.styles.global sub-package.
"""

from .colors import (
    BACKGROUND_COLOR,
    BORDER_COLOR,
    CONTAINER_BG_COLOR,
    MUTED_TEXT_COLOR,
    PRIMARY_ACCENT_COLOR,
    PRIMARY_HOVER_COLOR,
    SECONDARY_ACCENT_COLOR,
    SECONDARY_HOVER_COLOR,
    TEXT_COLOR,
)
from .effects import apply_shadow_effect
from .themes import DARK_QSS, LIGHT_QSS
from .widgets import (
    DARK_TOGGLE_BUTTON_QSS,
    LIGHT_TOGGLE_BUTTON_QSS,
    SCRIPT_HEADER_STYLE,
    SECONDARY_BUTTON_STYLE,
    SECTION_HEADER_STYLE,
    START_GREEN_STYLE,
    START_RED_STYLE,
    SUB_HEADER_STYLE,
    SUCCESS_BUTTON_STYLE,
)

__all__ = [
    "apply_shadow_effect",
    "PRIMARY_ACCENT_COLOR",
    "PRIMARY_HOVER_COLOR",
    "SECONDARY_ACCENT_COLOR",
    "SECONDARY_HOVER_COLOR",
    "BACKGROUND_COLOR",
    "CONTAINER_BG_COLOR",
    "TEXT_COLOR",
    "MUTED_TEXT_COLOR",
    "BORDER_COLOR",
    "DARK_TOGGLE_BUTTON_QSS",
    "LIGHT_TOGGLE_BUTTON_QSS",
    "SUCCESS_BUTTON_STYLE",
    "SECONDARY_BUTTON_STYLE",
    "SECTION_HEADER_STYLE",
    "SUB_HEADER_STYLE",
    "SCRIPT_HEADER_STYLE",
    "START_RED_STYLE",
    "START_GREEN_STYLE",
    "DARK_QSS",
    "LIGHT_QSS",
]
